### ISSUE TITLE
A PermissionError

### ISSUE THREAD

**Issue by WJluluxiu** [YoshitakaMo/localcolabfold#1]
![image](https://user-images.githubusercontent.com/89892117/132943369-29518164-6ab3-4474-af8c-aacf0076ac76.png)

**Comment by SJKbiophy6** [comment]
I had exactly the same error messages and Aborted (core dumped).

**Comment by CYP152N1** [comment]
I think the installation (bash install_colabfold_linux.sh) was performed on superuser account (spuser),
However you perform the localcolabfold on the other user.

why don't you change the Permission of home/spuser/colabfold/ using "chmod",
or change the "output_dir", which located on "runner.py line 195", to the permitted directory 

for example 
from
output_dir = 'prediction_' + jobname + '_' + cf.get_hash(full_sequence)[:5]
to
output_dir = '/home/#name of user to perform localcolabfold#/prediction/' + jobname + '_' + cf.get_hash(full_sequence)[:5]

**Comment by CYP152N1** [comment]
if you change output_dir from relative path to absolute path, 
you should change "runner.py line 821 to 840" to shown below

if use_ptm:
  print("predicted alignment error")
  cf.plot_paes([outs[k]["pae"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
  plt.savefig(output_dir+'/predicted_alignment_error.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))
  # plt.show()

print("predicted contacts")
cf.plot_adjs([outs[k]["adj"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_contacts.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()

print("predicted distogram")
cf.plot_dists([outs[k]["dists"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_distogram.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()

print("predicted LDDT")
cf.plot_plddts([outs[k]["plddt"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_LDDT.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()

**Comment by CYP152N1** [comment]
If you change output_dir from relative path to absolute path,
you need to change  "runner.py line 821 to 840" to shown below 

if use_ptm:
  print("predicted alignment error")
  cf.plot_paes([outs[k]["pae"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
  plt.savefig(output_dir+'/predicted_alignment_error.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))

print("predicted contacts")
cf.plot_adjs([outs[k]["adj"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_contacts.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))

print("predicted distogram")
cf.plot_dists([outs[k]["dists"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_distogram.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))

print("predicted LDDT")
cf.plot_plddts([outs[k]["plddt"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(output_dir+'/predicted_LDDT.png', bbox_inches = 'tight', dpi=np.maximum(200,dpi))

**Comment by SJKbiophy6** [comment]
My error messages are related to tensorflow. 
2021-09-13 11:27:00.157334: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-09-13 11:27:00.157381: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:113] Check failed: stream->parent()->GetBlasGemmAlgorithms(&algorithms)

any help?

**Comment by WJluluxiu** [comment]
I performed installation on root account. But there is another issue, i can not even normally run the runner.py !!! Reinstallation could not even solve this problem.
![image](https://user-images.githubusercontent.com/89892117/133030947-fbbb1c75-c318-4e07-8c8a-8618f1a097b9.png)

**Comment by WJluluxiu** [comment]
> My error messages are related to tensorflow.
> 2021-09-13 11:27:00.157334: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
> 2021-09-13 11:27:00.157381: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:113] Check failed: stream->parent()->GetBlasGemmAlgorithms(&algorithms)
> 
> any help?

no solution yet. it seems that GPUs are detected but not initiated.

**Comment by CYP152N1** [comment]
I am sorry; my writing might have confused you.
I have several question to solve your problem.

Could you tell us your OS?

On your first try, "bash install_colabfold_linux.sh" was performed on "spuser".
Was "colabfold-conda/bin/python3.7 runner.py" performd on "spuser"?

I think you installed on spuser, but you performed localcolabfold the other user.
because you have no permission although you had created /home/spuser/colabfold by installer.
I suggested to change the "output_dir in "runner.py" to permitted directory or change permission by 'chmod'
If you have another user of localcolabfold on your computer, you might not overwrite runner.py, and create and performed runner_XXX.py by copy.

I think you might not install the localcolabfold on root directory.

**Comment by WJluluxiu** [comment]
> I am sorry; my writing might have confused you.
> I have several question to solve your problem.
> 
> Could you tell us your OS?
> 
> On your first try, "bash install_colabfold_linux.sh" was performed on "spuser".
> Was "colabfold-conda/bin/python3.7 runner.py" performd on "spuser"?
> 
> I think you installed on spuser, but you performed localcolabfold the other user.
> because you have no permission although you had created /home/spuser/colabfold by installer.
> I suggested to change the "output_dir in "runner.py" to permitted directory or change permission by 'chmod'
> If you have another user of localcolabfold on your computer, you might not overwrite runner.py, and create and performed runner_XXX.py by copy.
> 
> I think you might not install the localcolabfold on root directory.

thanks a lot for you quedtions.

1. I use mobaXterm to connect the station, the OS is:
![image](https://user-images.githubusercontent.com/89892117/133044256-082b1579-8f75-4457-a9ec-2d884ae77dc5.png)

2. The whole installation process was performed with root privileges, so when running on spuser account it shows a Permission issue, shifting to root account can solve this.

3. i dont really understand "not install the localcolabfold on root directory.", could you be more specific?

**Comment by CYP152N1** [comment]
Thanks for your answer.

2. 
Dose it mean installation was performed by "sudo bash install_colabfold_linux.sh" ?
You try "(sudo) chmod 777 /home/spuser/colabfold"
or change the "output_dir in "runner.py of line 195" to permitted directory ,and change "runner.py of line 821 to 840 to shown previous"

3.
The creator of localcolabfold described on README
"$ bash install_colabfold_linux.sh"
it ($) means the installer was created for local-user not for superuser.

**Comment by WJluluxiu** [comment]
> Thanks for your answer.
> 
> 
> Dose it mean installation was performed by "sudo bash install_colabfold_linux.sh" ?
> You try "(sudo) chmod 777 /home/spuser/colabfold"
> or change the "output_dir in "runner.py of line 195" to permitted directory ,and change "runner.py of line 821 to 840 to shown previous"
> 
> 
> The creator of localcolabfold described on README
> "$ bash install_colabfold_linux.sh"
> it ($) means the installer was created for local-user not for superuser.

actually i log in as "spuser" account, and use "su root" before installing, the installation command is still "bash install_colabfold_linux.sh". And i am sorry for your misunderstanding of "spuser", it is just an user name, not "the superuser".
Actually my current question is "FileNotFoundError: [Errno 2] No such file or directory: './alphafold/data/params/params_model_5_ptm.npz'", re-installation can not solve. i dont konw why this happened.

**Comment by CYP152N1** [comment]
OK. I had already understood. 
In this case (su root), 
 "# bash install_colabfold_linux.sh"
you should not install colabfold in root.

The creator of localcolabfold described on README
"$ bash install_colabfold_linux.sh"
it ($) means the installer was created for local-user not for superuser(root).

**Comment by WJluluxiu** [comment]
> OK. I had already understood.
> In this case (su root),
> "# bash install_colabfold_linux.sh"
> you should not install colabfold in root.
> 
> The creator of localcolabfold described on README
> "$ bash install_colabfold_linux.sh"
> it ($) means the installer was created for local-user not for superuser(root).

thanks for this, i have successfully installed colabfold on the local-user "spuser". but there is still a file-missing problem, do you know how to solve this?
![image](https://user-images.githubusercontent.com/89892117/133069118-226a9b8a-f134-4e3f-bde5-8cbf819fd4b9.png)

**Comment by CYP152N1** [comment]
can you try 
$ ls /home/spuser/colabfold/alphafold/data/params

There is something to strange why params_model_5_ptm.npz not params_model_1_ptm.npz.
I think the error was caused by curl.
did you perform "$ sudo yum install curl wget" in the case of RHEL7?
if you have apt-get, "$ sudo apt -y install curl wget" will be work.

**Comment by WJluluxiu** [comment]
> can you try
> $ ls /home/spuser/colabfold/alphafold/data/params
> 
> There is something to strange why params_model_5_ptm.npz not params_model_1_ptm.npz.
> I think the error was caused by curl.
> did you perform "$ sudo yum install curl wget" in the case of RHEL7?
> if you have apt-get, "$ sudo apt -y install curl wget" will be work.

there is nothing under my /home/spuser/colabfold/alphafold/data/params. Do you mean perform "$ sudo yum install curl wget" and re-install colabfold?

**Comment by CYP152N1** [comment]
can you try 
"$ curl -h" 
to check that curl was installed  

I think you should read README more. 

For Linux
Make sure curl and wget commands are already installed on your PC. 
If not present, you need install them at first. "For Ubuntu", type sudo apt -y install curl wget.

I think your OS is not Ubuntu.
You cannot use "apt-get" in default, if you have installed "apt-get" by "yum".
Red Hat 4.8.X means RHEL7. 
The default installer is "yum"
you need to change "apt-get" to "yum" 

after the "$sudo yum install curl",
you try "$ curl -h"
I think the help of curl will be observed.
Now you can re-install colabfold.

or 
copy params_model_X_ptm.npz from alphafold into /home/spuser/colabfold/alphafold/data/params
X=1, 2, 3, 4, 5

**Comment by WJluluxiu** [comment]
> can you try
> "$ curl -h"
> to check that curl was installed
> 
> I think you should read README more.
> 
> For Linux
> Make sure curl and wget commands are already installed on your PC.
> If not present, you need install them at first. "For Ubuntu", type sudo apt -y install curl wget.
> 
> I think your OS is not Ubuntu.
> You cannot use "apt-get" in default, if you have installed "apt-get" by "yum".
> Red Hat 4.8.X means RHEL7.
> The default installer is "yum"
> you need to change "apt-get" to "yum"
> 
> after the "$sudo yum install curl",
> you try "$ curl -h"
> I think the help of curl will be observed.
> Now you can re-install colabfold.
> 
> or
> copy params_model_X_ptm.npz from alphafold into /home/spuser/colabfold/alphafold/data/params
> X=1, 2, 3, 4, 5

problem solved, but there is still tensorflow error remained.
![image](https://user-images.githubusercontent.com/89892117/133086853-d5608202-13fe-4d2b-ab79-01a661aa6eb2.png)

**Comment by WJluluxiu** [comment]
> can you try
> "$ curl -h"
> to check that curl was installed
> 
> I think you should read README more.
> 
> For Linux
> Make sure curl and wget commands are already installed on your PC.
> If not present, you need install them at first. "For Ubuntu", type sudo apt -y install curl wget.
> 
> I think your OS is not Ubuntu.
> You cannot use "apt-get" in default, if you have installed "apt-get" by "yum".
> Red Hat 4.8.X means RHEL7.
> The default installer is "yum"
> you need to change "apt-get" to "yum"
> 
> after the "$sudo yum install curl",
> you try "$ curl -h"
> I think the help of curl will be observed.
> Now you can re-install colabfold.
> 
> or
> copy params_model_X_ptm.npz from alphafold into /home/spuser/colabfold/alphafold/data/params
> X=1, 2, 3, 4, 5

hi there, on your own home page i noticed that you mentioned to use .fasta file on localcolabfold. May i ask how, exactly? Because if i directly modify the variables such as sequence = 'PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK', jobname = "test", and etc. in runner.py code, it may throw a Syntaxerror.

**Comment by CYP152N1** [comment]
>hi there, on your own home page i noticed that you mentioned to use .fasta file on localcolabfold. May i ask how, exactly?
>Because if i directly modify the variables such as sequence = 'PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK', jobname = "test", and etc. in runner.py code, it may throw a Syntaxerror.

I will show you one of example.
ttps://github.com/CYP152N1/localcolabfold/blob/main/runner_log_arg.py

Sorry I don't know the tensorflow error of alphafold.
you can get some advice at
https://github.com/deepmind/alphafold/issues

**Comment by CYP152N1** [comment]
>hi there, on your own home page i noticed that you mentioned to use .fasta file on localcolabfold. May i ask how, exactly? Because if i directly modify the variables such as sequence = 'PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK', jobname = "test", and etc. in runner.py code, it may throw a Syntaxerror.

I remake runner.py to import .fasta file, because runner_log_arg.py was prepared from old runner.py
https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_fasta.py

If you don't use argument, you can change several options at the top of runner_align.py
https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_align.py

**Comment by WJluluxiu** [comment]
> > hi there, on your own home page i noticed that you mentioned to use .fasta file on localcolabfold. May i ask how, exactly? Because if i directly modify the variables such as sequence = 'PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK', jobname = "test", and etc. in runner.py code, it may throw a Syntaxerror.
> 
> I remake runner.py to import .fasta file, because runner_log_arg.py was prepared from old runner.py
> https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_fasta.py
> 
> If you don't use argument, you can change several options at the top of runner_align.py
> https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_align.py

hi CYP152N1, i tried your "runner_fasta.py". According to your code, first i need to rename the protein as "test.fasta", and upload it to the /fasta/ fold, then perform the "runner_fasta.py", right? But seems that it can only predict a single protein, how about the complex?

**Comment by WJluluxiu** [comment]
> > hi there, on your own home page i noticed that you mentioned to use .fasta file on localcolabfold. May i ask how, exactly? Because if i directly modify the variables such as sequence = 'PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK', jobname = "test", and etc. in runner.py code, it may throw a Syntaxerror.
> 
> I remake runner.py to import .fasta file, because runner_log_arg.py was prepared from old runner.py
> https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_fasta.py
> 
> If you don't use argument, you can change several options at the top of runner_align.py
> https://github.com/CYP152N1/localcolabfold/blob/patch-1/runner_align.py

found the way to complexes, thanks

**Comment by CYP152N1** [comment]
No. in my method, you can import your .fasta file by -f argument.
you need to select relative path.  
ex) 
colabfold-conda/bin/python3.7 runner_fasta.py path/to/fasta/nameofprotein.fasta 

If you use .fasta file as import, the name of output directory was changed to file name of fasta.
you can change the name of outputdirectory, -jo argument (ex: -jo proteinname)

Importing argument of  fasta file was already supported on default localcolafold (runner_af2advanced.py)
If you use runner_fasta.py, please move to my fork to prevent confusion.

**Comment by WJluluxiu** [comment]
> My error messages are related to tensorflow.
> 2021-09-13 11:27:00.157334: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
> 2021-09-13 11:27:00.157381: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:113] Check failed: stream->parent()->GetBlasGemmAlgorithms(&algorithms)
> 
> any help?

hi, there, do you still have that problem? i successfully run the program by updating my GPU driver.

**Comment by CYP152N1** [comment]
I think SJKbiophy6's problem was already solved by #2(closed).
https://github.com/YoshitakaMo/localcolabfold/issues/2

The problem of "PermissionError #1" was also solved.
The issue will be close.
