### ISSUE TITLE
tol argument requires float type in runner_af2advanced.py

### ISSUE THREAD

**Issue by zach-hensel** [YoshitakaMo/localcolabfold#10]
Apologies for not doing this correctly but my local advanced.py has other differences. For recycle tolerance to work, this must be added:
```
parser.add_argument("--tol", default=0, type=float, help="tolerance for deciding when to stop (CA-RMS between recycles)")
```
Attached is a patch ([fix_tol.txt](https://github.com/YoshitakaMo/localcolabfold/files/7253164/fix_tol.txt)) to make this change and also two others in my local advanced script that are useful for me:
1. Reuse existing pickle.msa or specify a directory where one is; should add a check that the sequence matches
2. Change --num_models behavior to take a list of models to run as a string e.g. "--num_models 35" runs models 3 and 5 only.

Thank you for making this available -- very nice to get around the colab size limit and increasing policing of interactive use; this installed with no trouble on google cloud program deep learning VMs (except for the same array/list issue for relaxation) using the default K40 and A100 configurations.

**Comment by YoshitakaMo** [comment]
Thank you for your suggestion. I'll check `fix_tol.txt` and implement them but am busy for a while. Please wait a little longer...
