### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by biotech70** [YoshitakaMo/localcolabfold#105]
**What is your question?**
During the execution of the Local-ColabFold by the following command, it encounters a problem. The error file was attached.
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax --zip inputfile outputdir/

**Computational environment**
 - OS: [Ubuntu 22.04]
 - CUDA version if Linux (11.7)
 
[colabfold_error.txt](https://github.com/YoshitakaMo/localcolabfold/files/9283662/colabfold_error.txt)

**Comment by YoshitakaMo** [comment]
I guess there was an error when you download the alphafold2 weights parameters. Delete `/home/protein-institute/ROSETTA/rosetta_bin_linux_2020.08.61146_bundle/local-colabfold/colabfold_batch/colabfold` directory and run again.

**Comment by biotech70** [comment]
This is not possible because local-colabfold is installed in this directory

**Comment by biotech70** [comment]
The problem persists even after removing the colabfold directory.

**Comment by biotech70** [comment]
There is no problem with my network, but I have no idea why alphafold weights download was disrupted.

**Comment by YoshitakaMo** [comment]
I have no idea to fix it. Try deleting the colabfold_batch directory and install again. I think the error is not due to the installation itself.

**Comment by biotech70** [comment]
thanks for your attention, I hope to solve this problem

**Comment by biotech70** [comment]
Is it possible to manually download alphafold parameters? In Discord, some have given this answer to solve this problem:
*Taking a step back: Is your machine connected to the web (i.e. port 80 & 443, regardless of port 22 & co.)? I.e. if you ping google.com, do you get something?
If so: https://github.com/sokrypton/ColabFold/blob/4b86ef10e319cfb6102dbb676e3720c5d9bab9e4/colabfold/download.py#L15 has the urls, so just curl them.*

**Comment by YoshitakaMo** [comment]
On Linux, the parameter files will be downloaded in `.../local-colabfold/colabfold_batch/colabfold` and the directory should be like this:

```
colabfold_batch
├── bin
│   └── colabfold_batch
├── colabfold
│   └── params
│       ├── download_complexes_finished.txt
│       ├── download_complexes_multimer-v2_finished.txt
│       ├── download_finished.txt
│       ├── LICENSE
│       ├── params_model_1_multimer.npz
│       ├── params_model_1_multimer_v2.npz
│       ├── params_model_1.npz
│       ├── params_model_1_ptm.npz
│       ├── params_model_2_multimer.npz
│       ├── params_model_2_multimer_v2.npz
│       ├── params_model_2.npz
│       ├── params_model_2_ptm.npz
│       ├── params_model_3_multimer.npz
│       ├── params_model_3_multimer_v2.npz
│       ├── params_model_3.npz
│       ├── params_model_3_ptm.npz
│       ├── params_model_4_multimer.npz
│       ├── params_model_4_multimer_v2.npz
│       ├── params_model_4.npz
│       ├── params_model_4_ptm.npz
│       ├── params_model_5_multimer.npz
│       ├── params_model_5_multimer_v2.npz
│       ├── params_model_5.npz
│       └── params_model_5_ptm.npz
├── colabfold-conda
│   ├── bin
...
│   └── x86_64-conda-linux-gnu
├── conda
│   ├── bin
...
│   └── x86_64-conda-linux-gnu
├── matplotlib
│   ├── fontlist-v310.json
│   └── tex.cache
└── update_linux.sh
```

So, If you want to download the parameters manually, 

```bash
mkdir -p /home/protein-institute/ROSETTA/rosetta_bin_linux_2020.08.61146_bundle/local-colabfold/local-colabfold/colabfold_batch/colabfold
cd /home/protein-institute/ROSETTA/rosetta_bin_linux_2020.08.61146_bundle/local-colabfold/local-colabfold/colabfold_batch/colabfold
wget https://storage.googleapis.com/alphafold/alphafold_params_colab_2022-03-02.tar
tar -xvf alphafold_params_colab_2022-03-02.tar
touch download_complexes_multimer-v2_finished.txt
wget https://storage.googleapis.com/alphafold/alphafold_params_colab_2021-10-27.tar
tar -xvf alphafold_params_colab_2021-10-27.tar
touch download_complexes_multimer-v1_finished.txt
wget https://storage.googleapis.com/alphafold/alphafold_params_2021-07-14.tar
tar -xvf alphafold_params_2021-07-14.tar
touch download_finished.txt
```

After executing the commands, make sure the parameters and the marker txt files are present in the directory.

**Comment by biotech70** [comment]
![1](https://user-images.githubusercontent.com/73783725/184682521-36396ebe-dacb-4085-a670-bd4e78ef3dcf.png)
![2](https://user-images.githubusercontent.com/73783725/184682534-52d3fdc7-b335-4f72-8ef6-6ef69f59d88b.png)
![params-path-contents](https://user-images.githubusercontent.com/73783725/184682559-99b5571b-27e6-4d50-accc-dfd43da41a5e.png)

**Comment by biotech70** [comment]
I uploaded the contents of the params directory, as well as the fasta file and error file.

**Comment by YoshitakaMo** [comment]
Usually, the header line in FASTA format must have some character after the `>`. For example, `>test`.

**Comment by biotech70** [comment]
Thank you for your patience and response.
![error](https://user-images.githubusercontent.com/73783725/184854936-cc10c4ce-2c0e-483b-9473-36323421440a.png)

**Comment by biotech70** [comment]
From the source code, I installed Cuda version 11.7. Additionally, Cuda 11.1 was installed during the installation of local-colabfold using Conda.
![cuda](https://user-images.githubusercontent.com/73783725/184859009-b70a39c3-cf16-4330-b7fe-474b32b600ff.png)

**Comment by YoshitakaMo** [comment]
Please show me the output of `nvcc --version` (or `/usr/local/cuda/bin/nvcc --version`), not of `nvidia-smi`.

**Comment by biotech70** [comment]
ls -ltr for params directory.
![params path](https://user-images.githubusercontent.com/73783725/184925599-2d8de203-f745-4faf-9806-f67bc38b5e09.png)

**Comment by YoshitakaMo** [comment]
Hm, your environment seems no problem. My machine is also cuda_11.7.
When someone had a similar issue to this before, reinstalling `colabfold_batch` or rebooting the machine was the solution. Once you have moved that `params` directory somewhere else, delete that `colabfold_batch` directory, reinstall, reboot, put the `params` directory back in, and try again the prediction.

**Comment by biotech70** [comment]
I have not moved the params path. The problem persists despite rebooting the system.
![params path](https://user-images.githubusercontent.com/73783725/184933794-0b94dff3-4b83-4935-8713-8eadcc76a2ac.png)

**Comment by biotech70** [comment]
Even by reinstalling the colabfold, the problem was not solved.

**Comment by YoshitakaMo** [comment]
I've just realized now that your GPU's VRAM 2048MiB (= 2GiB) is too small to run (local)colabfold. `nvidia-smi` showed the capacity. That's the cause of `RESOURCE_EXHAUSTED: Out of memory while trying to allocate 3145728 bytes.` error. Namely, the sequence you want to predict is beyond the limitation of your GPU. The GPU can only predict up to about 20-30 amino acids. You need a more high-grade GPU (e.g. RTX3060, VRAM 12GB) to run ~900 a.a..

**Comment by biotech70** [comment]
My goal at this point is to make sure the Local-colabfold is installed correctly. Even for sequences of 8 amino acids, I receive the same error.

**Comment by biotech70** [comment]
even for one residue, I get the same error.
[error.txt](https://github.com/YoshitakaMo/localcolabfold/files/9358682/error.txt)

**Comment by YoshitakaMo** [comment]
> My goal at this point is to make sure the Local-colabfold is installed correctly.

Add `--cpu` option to run without GPU. If the prediction completes, the installation was finished correctly.

Since I haven't tested if AlphaFold/Colabfold works on a PC with such a small GPU, I can't provide further support.

**Comment by biotech70** [comment]
cool, local-colabfold executed.

**Comment by YoshitakaMo** [comment]
That's strange. Your openmm (simtk) module in the `colabfold-conda/lib/python3.7/site-packages` seems updated from version 7.5.1 for some reason. One solution is to install the version again in the colabfold's conda environment.

**Comment by biotech70** [comment]
I removed openmm v7.7 and installed v7.5.1 using conda install -c conda-forge openmm=7.5.1, but the error still persists.

**Comment by YoshitakaMo** [comment]
Is there really simtk directory in `colabfold-conda/lib/python3.7/site-packages`? Make sure your conda environment is colabfold-conda's conda.

**Comment by biotech70** [comment]
Yes, it is available in this directory.
![Untitled](https://user-images.githubusercontent.com/73783725/185372658-4019362a-20ff-46b4-9230-d6d3ac0fe5f9.png)

**Comment by YoshitakaMo** [comment]
No, there is no `simtk` directory in the screenshot.

**Comment by biotech70** [comment]
What is the best way to install the simtk in ubutnu 22.04?

**Comment by YoshitakaMo** [comment]
The `simtk` directory is installed by `conda install -c conda-forge openmm==7.5.1` as implemented in line 19 of the installation script `install_colabbatch_linux.sh`.
I guess you always turn on another conda environment, but it may do the installation harm. Please test the install script again after you deactivate your conda environment completely. If it is still not corrected, I am no longer able to point out what the cause is.

**Comment by biotech70** [comment]
it's my conda-env in bashrc file:
![conda-env](https://user-images.githubusercontent.com/73783725/185470657-291cbdd6-6522-438e-999c-07ff12606aac.png)

**Comment by biotech70** [comment]
> The `simtk` directory is installed by `conda install -c conda-forge openmm==7.5.1` as implemented in line 19 of the installation script `install_colabbatch_linux.sh`. I guess you always turn on another conda environment, but it may do the installation harm. Please test the install script again after you deactivate your conda environment completely. If it is still not corrected, I am no longer able to point out what the cause is.

The problem was solved by changing the Conda environment.

**Comment by YoshitakaMo** [comment]
Great! I'll update README.md to deactivate conda environment! Then, did your prediction work well with `--amber` and without `--cpu` for the test fasta file?

**Comment by biotech70** [comment]
> Great! I'll update README.md to deactivate conda environment! Then, did your prediction work well with `--amber` and without `--cpu` for the test fasta file?

just this command work for me:
colabfold_batch --amber --templates --num-recycle 1  --cpu  input output/
but with the below command I get an error:
colabfold_batch --amber --templates --num-recycle 1 --use-gpu-relax --cpu  input output/

**Comment by biotech70** [comment]
with --use-gpu-relax and without --cpu i get the below error:
![gpu error](https://user-images.githubusercontent.com/73783725/185657623-bdbba150-9a64-4cc6-bee4-be1ea9905ce5.png)

**Comment by biotech70** [comment]
even after running *pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html* i get same error.

**Comment by biotech70** [comment]
It would be great if you could provide an example fatsta file for both monomer and multimer local-collabfold modes. I currently want to run the multimer mode, but I don't know what features the fasta file should have, and I don't know how to specify the number of mers in the multimer mode?

**Comment by YoshitakaMo** [comment]
> `ERROR Jax could not find GPU.`

Then, it seems that your GPU does not support jax and you cannot execute localcolabfold using the GPU. Try on a computer with [GeForce 30 series](https://en.wikipedia.org/wiki/GeForce_30_series). But, all other functions are working!

**Comment by biotech70** [comment]
Thanks, Is the quality of the structures predicted by Alphafold installed from the source code different from the structures predicted by local-colabfold?

**Comment by biotech70** [comment]
Thanks, Is the quality of the structures predicted by Alphafold installed from the source code different from the structures predicted by local-colabfold?

**Comment by YoshitakaMo** [comment]
> Is the quality of the structures predicted by Alphafold installed from the source code different from the structures predicted by local-colabfold?

There's (almost) no difference between AlphaFold and (local)colabfold if MSAs used are the same since the engine of structure inference of colabfold is identical. The quality of structure mainly depends on the number of the MSAs.
