### ISSUE TITLE
Could not get MSA/templates (HHSearch failed)

### ISSUE THREAD

**Issue by agatawitkowska** [YoshitakaMo/localcolabfold#107]
On Windows 10 using WSL I'm trying to run:

```
~$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax --model-type AlphaFold2-multimer-v2 PDBID_6IWD.csv outputdir/ --cpu
```

using `PDBID_6IWD.csv`:

```
id,sequence
PDBID_6IWD,MVDATRVPMDERFRTLKKKLEEGMVFTEYEQIPKKKANGIFSTAALPENAERSRIREVVPYEENRVELIPTKENNTGYINASHIKVVVGGAEWHYIATQGPLPHTCHDFWQMVWEQGVNVIAMVTAEEEGGRTKSHRYWPKLGSKHSSATYGKFKVTTKFRTDSVCYATTGLKVKHLLSGQERTVWHLQYTDWPDHGCPEDVQGFLSYLEEIQSVRRHTNSMLEGTKNRHPPIVVHCSAGVGRTGVLILSELMIYCLEHNEKVEVPMMLRLLREQRMFMIQTIAQYKFVYQVLIQFLQNSRLI:MVDATRVPMDERFRTLKKKLEEGMVFTEYEQIPKKKANGIFSTAALPENAERSRIREVVPYEENRVELIPTKENNTGYINASHIKVVVGGAEWHYIATQGPLPHTCHDFWQMVWEQGVNVIAMVTAEEEGGRTKSHRYWPKLGSKHSSATYGKFKVTTKFRTDSVCYATTGLKVKHLLSGQERTVWHLQYTDWPDHGCPEDVQGFLSYLEEIQSVRRHTNSMLEGTKNRHPPIVVHCSAGVGRTGVLILSELMIYCLEHNEKVEVPMMLRLLREQRMFMIQTIAQYKFVYQVLIQFLQNSRLI:GHMAEPQRHTMLCMCCKCEARIELVVESSADDLRAFQQLFLNTLSFVCPWCASQQ:GHMAEPQRHTMLCMCCKCEARIELVVESSADDLRAFQQLFLNTLSFVCPWCASQQ
```

I'm getting:

```
2022-08-19 14:14:29,095 Running colabfold 1.3.0
2022-08-19 14:14:29,781 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
/home/username/.local/lib/python3.8/site-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
2022-08-19 14:14:32,042 Found 8 citations for tools or databases
2022-08-19 14:14:41,237 Query 1/1: PDBID_6IWD (length 716)
2022-08-19 14:14:42,611 Sleeping for 8s. Reason: PENDING
2022-08-19 14:14:51,872 Sleeping for 9s. Reason: RUNNING
2022-08-19 14:15:02,139 Sleeping for 10s. Reason: RUNNING
2022-08-19 14:15:13,409 Sleeping for 10s. Reason: RUNNING
2022-08-19 14:15:24,672 Sleeping for 9s. Reason: RUNNING
2022-08-19 14:15:34,928 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100%|██████████████████████████████████████████████████████████████| 300/300 [elapsed: 01:16 remaining: 00:00]
2022-08-19 14:16:22,815 Could not get MSA/templates for PDBID_6IWD: HHSearch failed:
stdout:


stderr:
- 14:16:20.510 INFO: /tmp/tmp3df2iks3/query.a3m is in A2M, A3M or FASTA format

- 14:16:20.684 INFO: Searching 20 database HHMs without prefiltering

- 14:16:20.684 INFO: Iteration 1

- 14:16:20.813 WARNING: database contains sequences that exceeds maximum allowed size (maxres = 20001). Maxres can be increased with parameter -maxres.

- 14:16:20.831 INFO: Scoring 20 HMMs using HMM-HMM Viterbi alignment

- 14:16:20.858 INFO: Alternative alignment: 0

- 14:16:21.276 INFO: 20 alignments done

- 14:16:21.276 INFO: Alternative alignment: 1

- 14:16:21.691 INFO: 20 alignments done

- 14:16:21.691 INFO: Alternative alignment: 2

- 14:16:21.921 INFO: 8 alignments done

- 14:16:21.921 INFO: Alternative alignment: 3

- 14:16:21.935 INFO: Realigning 28 HMM-HMM alignments using Maximum Accuracy algorithm

- 14:16:22.787 INFO: 28 sequences belonging to 28 database HMMs found with an E-value < 0.001

free(): invalid pointer

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.8/site-packages/colabfold/batch.py", line 1332, in run
    ) = get_msa_and_templates(
  File "/home/username/.local/lib/python3.8/site-packages/colabfold/batch.py", line 787, in get_msa_and_templates
    template_feature = mk_template(
  File "/home/username/.local/lib/python3.8/site-packages/colabfold/batch.py", line 165, in mk_template
    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
  File "/home/username/.local/lib/python3.8/site-packages/alphafold/data/tools/hhsearch.py", line 94, in query
    raise RuntimeError(
RuntimeError: HHSearch failed:
stdout:


stderr:
- 14:16:20.510 INFO: /tmp/tmp3df2iks3/query.a3m is in A2M, A3M or FASTA format

- 14:16:20.684 INFO: Searching 20 database HHMs without prefiltering

- 14:16:20.684 INFO: Iteration 1

- 14:16:20.813 WARNING: database contains sequences that exceeds maximum allowed size (maxres = 20001). Maxres can be increased with parameter -maxres.

- 14:16:20.831 INFO: Scoring 20 HMMs using HMM-HMM Viterbi alignment

- 14:16:20.858 INFO: Alternative alignment: 0

- 14:16:21.276 INFO: 20 alignments done

- 14:16:21.276 INFO: Alternative alignment: 1

- 14:16:21.691 INFO: 20 alignments done

- 14:16:21.691 INFO: Alternative alignment: 2

- 14:16:21.921 INFO: 8 alignments done

- 14:16:21.921 INFO: Alternative alignment: 3

- 14:16:21.935 INFO: Realigning 28 HMM-HMM alignments using Maximum Accuracy algorithm

- 14:16:22.787 INFO: 28 sequences belonging to 28 database HMMs found with an E-value < 0.001

free(): invalid pointer


2022-08-19 14:16:22,816 Done
```

I would appreciate any helpful advice.

**Comment by biotech70** [comment]
can you share with me your CSV file?

**Comment by agatawitkowska** [comment]
I pasted content of `PDBID_6IWD.csv` above (that's one I tried). Now also as a file: [PDBID_6IWD.csv](https://github.com/YoshitakaMo/localcolabfold/files/9386551/PDBID_6IWD.csv).

**Comment by biotech70** [comment]
its work for me

**Comment by agatawitkowska** [comment]
Sure. I do not expect problems with my `PDBID_6IWD.csv` or run command. Thanks anyway.

I guess there might be some "install"/dependencies problem which I'm not sure how to start debugging right now.

**Comment by lukaszjablonski** [comment]
@biotech70, did you run it on Windows 10 using WSL Ubuntu 20.04.4 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)?

**Comment by biotech70** [comment]
no

**Comment by biotech70** [comment]
please share the provided seq file that was used for structure prediction.

**Comment by IlyesAbdelhamid** [comment]
You will find the seq file in the attached document.


Sincerely,
Ilyes

**Comment by biotech70** [comment]
like below:
MKLGIIPYQEGTDIVYKNALQGQQEGKRPNLPQMEATHQIKSSVQGTSYEFVRTEDIPLNRRHFVYRPCS
ANPFFTILGYGCTEYPFDHSGMSVMDRSEGLSISRDGNDLVSVPDQYGWRTARSDVCIKEGMTYWEVEVI
RGGNKKFADGVNNKENADDSVDEVQSGIYEKMHKQVNDTPHLRFGVCRREASLEAPVGFDVYGYGIRDIS
LESIHEGKLNCVLENGSPLKEGDKIGFLLSLPSIHTQIKQAKEFTKRRIFALNSHMDTMNEPWREDAENG
PSRKKLKQETTNKEFQRALLEDIEYNDVVRDQIAIRYKNQLFFEATDYVKTTKPEYYSSDKRERQDYYQL
EDSYLAIFQNGKYLGKAFENLKPLLPPFSELQYNEKFYLGYWQHGEARDESNDKNTTSAKKKKQQQKKKK
GLILRNKYVNNNKLGYYPTISCFNGGTARIISEEDKLEYLDQIRSAYCVDGNSKVNTLDTLYKEQIAEDI
VWDIIDELEQIALQQ:MNILLQDPFAVLKEHPEKLTHTIENPLRTECLQFSPCGDYLALGCANGALVIYDMDTFRPICVPGNMLGA
HVRPITSIAWSPDGRLLLTSSRDWSIKLWDLSKPSKPLKEIRFDSPIWGCQWLDAKRRLCVATIFEESDA
YVIDFSNDPVASLLSKSDEKQLSSTPDHGYVLVCTVHTKHPNIIIVGTSKGWLDFYKFHSLYQTECIHSL
KITSSNIKHLIVSQNGERLAINCSDRTIRQYEISIDDENSAVELTLEHKYQDVINKLQWNCILFSNNTAE
YLVASTHGSSAHELYIWETTSGTLVRVLEGAEEELIDINWDFYSMSIVSNGFESGNVYVWSVVIPPKWSA
LAPDFEEVEENVDYLEKEDEFDEVDEAEQQQGLEQEEEIAIDLRTREQYDVRGNNLLVERFTIPTDYTRI
IKMQSS

**Comment by IlyesAbdelhamid** [comment]
I forgot to mention that I modified the code internally to get the same
required format as you showed above.


Sincerely,
Ilyes

**Comment by biotech70** [comment]
I don't understand, do you get an error when you use a CSV file where the sequences are separated by *:* symbol?

**Comment by biotech70** [comment]
please provide information on your OS and GPU

**Comment by IlyesAbdelhamid** [comment]
You will find in the attached document the output of ColabFold.
It is the same problem as the one I initially reported: Could not get
MSA/templates for PDBID_6WOV: HHSearch failed

I use a multi-GPU sub-cluster "Alpha Centauri".. It has 34 nodes, each
with:
- 8 x NVIDIA A100-SXM4 (40 GB RAM)
- 2 x AMD EPYC CPU 7352 (24 cores) @ 2.3 GHz with multi-threading enabled
- 1 TB RAM
- 3.5 TB /tmp local NVMe device


- Sincerely,
- Ilyes

**Comment by IlyesAbdelhamid** [comment]
I've been computing multimer prediction with the format I sent you in the
fasta file.



Sincerely,
Ilyes

**Comment by biotech70** [comment]
oh so good

**Comment by IlyesAbdelhamid** [comment]
Do you have any idea what could be the issue ?


Sincerely,
Ilyes

**Comment by biotech70** [comment]
It may be related to the headers of your sequences.

**Comment by biotech70** [comment]
Did you use the CSV file which I shared with you to determine the structure?

**Comment by IlyesAbdelhamid** [comment]
Yes. Please see the output in the attached document.


Sincerely,
Ilyes

**Comment by biotech70** [comment]
Ok, the most crucial option in prediction of structures by a CSV file is to use *:* symbol for the separation of sequences in multimeric form.

**Comment by IlyesAbdelhamid** [comment]
Yes the ':' is in the CSV file you sent to me.
Please if you have any idea what could be the issue let me know. Thank you!


Sincerely,
Ilyes

**Comment by biotech70** [comment]
I listed below some things that are important in prediction using local-colabfold:
1- JAX version
2- GPU config
3- The size of the target sequence
4- The version of local-colabfold (because some people get different output from the old version of colabfold compared to the newer version of colabfold)

**Comment by IlyesAbdelhamid** [comment]
Thank you, see reply below.


Sincerely,
Ilyes

---------- Forwarded message ---------
De : mohammad mahmoudi gomari ***@***.***>
Date: mar. 11 oct. 2022 à 13:52
Subject: Re: [YoshitakaMo/localcolabfold] Could not get MSA/templates
(HHSearch failed) (Issue #107)
To: YoshitakaMo/localcolabfold ***@***.***>
Cc: IlyesAbdelhamid ***@***.***>, Comment <
***@***.***>


I listed below some things that are important in prediction using
local-colabfold:
1- JAX version
2- GPU config

REPLY: I hardly believe that the issue is due to JAX and GPU config because
I've been predicting thousands of structures no problem. It's the only time
I have such an issue.

3- The size of the target sequence

REPLY: Protein  A is 505aa long and Protein B is 426aa long. I have dealt
with pairs of proteins with much longer sequences with no problem.

4- The version of local-colabfold (because some people get different output
from the old version of colabfold compared to the newer version of
colabfold)

REPLY: I would say it is the most plausible option. I use colabfold *1.3.0*.
Have you tried to run my prediction with my parameters on your own
local-colabfold version as a sanity check ?
Command line:
colabfold_batch --num-recycle 3 --templates --model-type
AlphaFold2-multimer-v2 --rank intscore 6WOV.csv outputdir/
