### ISSUE TITLE
What is the best way to upgrade local-colabfold 1.3 to version 1.4?Question:

### ISSUE THREAD

**Issue by biotech70** [YoshitakaMo/localcolabfold#109]
**What is your question?**
What is the best way to upgrade local-colabfold 1.3 to version 1.4?
**Computational environment**
 - OS: [Ubuntu 22.04]
 - CUDA version if Linux (11.7)

According to your instructions, I have upgraded localcolabfold version 1.3 to version 1.4. The command was executed successfully, but when running the tool, the number 1.3 is seen in the version section of the tool.

**Comment by YoshitakaMo** [comment]
Sorry for the confusion, but the behavior is normal. The versions of them are independent. Enjoy it!

**Comment by biotech70** [comment]
Thanks
