### ISSUE TITLE
Run time error with jaxlib

### ISSUE THREAD

**Issue by valvanom** [YoshitakaMo/localcolabfold#110]
I have installed colabfold in a linux desktop following the instructions. After running colabfold_batch I get the following errors:
"2022-09-17 23:40:34,073 Running colabfold 1.3.0 (d991ad9b2d14fbcaf660a6955a9a9de34b4f5eb8)
Traceback (most recent call last):
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1715, in main
    from jax.lib import xla_bridge
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/mvlab/colabfold/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/jax/_src/lib/__init__.py", line 98, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source."

I try to install with a modified script to prevent CUDA installations, as follows:
conda install -c conda-forge python=3.7  openmm==7.5.1 pdbfixer -y
XXXXXXXXXXXXXXX
2colabfold-conda/bin/python3.7 -m pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"
colabfold-conda/bin/python3.7 -m pip install --upgrade pip
colabfold-conda/bin/python3.7 -m pip install --upgrade "jax[cpu]" 
XXXXX
But no luck. Any ideas?

**Comment by EgonHeuson** [comment]
Hello, 
Same error for me here. I running the script on a local server with an intel Xeon. If someone has an idea here :-)
`RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.`

**Comment by YoshitakaMo** [comment]
@EgonHeuson  It seems a different error. I guess your intel Xeon server may be so old that it's not compatible with the latest jaxlib that can be installed through pip. Tell me the CPU model name `$ cat /proc/cpuinfo | grep "model name"`.

**Comment by EgonHeuson** [comment]
Thank you very much for your reply 😃. It's what I was afraid of 😓. 
It's a 24-cores Xeon E5-2620 CPU
```
cat /proc/cpuinfo | grep "model name"
model name	: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
```
I have to precise that I run ColabFoldLocal on a virtual machine running a Debian 11.6, if it may cause some issues too?

**Comment by YoshitakaMo** [comment]
@EgonHeuson 
Is this the one you use?
https://ark.intel.com/content/www/us/en/ark/products/83352/intel-xeon-processor-e52620-v3-15m-cache-2-40-ghz.html
But this is 6-core/12-thread model. 

Alternatively, the following command can be used to check whether the "avx" instruction is supported on your CPU.
```
$ cat /proc/cpuinfo | grep "model flags" | grep "avx"
flags           : fpu vme ...  popcnt aes xsave avx f16c rdrand  ... bmi1 avx2 smep bmi2
```

If you find a string "avx" or "avx2", your CPU support AVX.

> I have to precise that I run ColabFoldLocal on a virtual machine running a Debian 11.6, if it may cause some issues too?

I think it's not a problem... but I didn't test it on a virtual machine. Is your main OS Windows?

**Comment by EgonHeuson** [comment]
Yes exactly. It's just that I have 4 of them :-)

> Alternatively, the following command can be used to check whether the "avx" instruction is supported on your CPU.

```
$ cat /proc/cpuinfo | grep "model flags" | grep "avx"
flags           : fpu vme ...  popcnt aes xsave avx f16c rdrand  ... bmi1 avx2 smep bmi2
```
In my case this command returns nothing. 😥
However if I just use `grep avx /proc/cpuinfo`, I get:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 **_avx2_** smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts
```
So I'd say it's avx2 in my case :-)

And about my VM, it's running on a Proxmox server :-)

**Comment by YoshitakaMo** [comment]
Oops, I made a mistake. The correct command was `cat /proc/cpuinfo | grep "flags" | grep "avx"`. But anyway, your CPU has avx2 support. I'm sorry but I could not find this solution😥
I guess If you could run localcolabfold without a virtual machine, jax and jaxlib would work fine...

**Comment by EgonHeuson** [comment]
Thank you for your help! ☺️ I'll have a look on how I can go around this problem. I checked what it says when I ask the info inside the virtual machine and it says "kvm CPU". Maybe I whall find a way to transfer avx support to the VM? :-)
