### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443)

### ISSUE THREAD

**Issue by gancao** [YoshitakaMo/localcolabfold#114]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /alphafold/alphafold_params_colab_2022-03-02.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2ea819bf10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

How to set the host-url?

**Comment by YoshitakaMo** [comment]
The error tells you that your calculation node (or machine) couldn't download `alphafold_params_colab_2022-03-02.tar` for the first run. Make sure your machine and network have access to the Internet. It has nothing to do with `--host-url`.

**Comment by TKsh6** [comment]
so if I manually downloaded alphafold_params_colab_2022-03-02.tar and `tar -xf alphafold_params_colab_2022-12-06.tar -C /root/hjx/localcolabfold/colabfold-conda/data ` but it still call this error.
```
colabfold_batch \
  --model-type alphafold2_multimer_v3 \
  --amber \
  --templates \
  --num-recycle 12 \
  --num-ensemble 1 \
  --num-models 5 \
  --random-seed 42 \
  --save-recycles \
  --save-single-representations \
  --save-pair-representations \
  --stop-at-score 100 \
  --data /root/hjx/localcolabfold/colabfold-conda/data 
  /root/private_data/colabfold/test.fa /root/hjx/multimers_pre/01_20250523
```
how can I do to solve this?
