### ISSUE TITLE
ValueError: Could not find CIFs in ...

### ISSUE THREAD

**Issue by TieliangGan** [YoshitakaMo/localcolabfold#115]
**What is your question?**
The program raise this error all of a sudden. The problem pop up today and it ran quite well before.  I saw the similar issue here but I didn't see any new version released so I assume this is not the problem of my current version? 

**Computational environment**
 - OS: centOS7
 - CUDA version if Linux 11.1.74

**Comment by TieliangGan** [comment]
To be clearer, the current version I am using is:
Running colabfold 1.3.0 (f1b66cf202cee52d6a5c86cc4e8dd4ae1a048645)
I saw similar issue regarding the confusion version number but I assume the hash value can prove my current version is 1.4.0 :)

and more precisely, the error the program is raising is:
Running colabfold 1.3.0 (f1b66cf202cee52d6a5c86cc4e8dd4ae1a048645)
2022-10-16 09:32:00,649 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-10-16 09:32:02,346 Found 8 citations for tools or databases
2022-10-16 09:32:06,077 Query 1/1: AA2AR_Nb.AD101 (length 534)
COMPLETE: 100%|██████████████████████| 300/300 [elapsed: 00:05 remaining: 00:00]

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat ‘/home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101/pdb70_a3m.ffindex’: No such file or directory

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat ‘/home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_102/pdb70_a3m.ffindex’: No such file or directory
2022-10-16 09:32:12,472 Could not find CIFs in /home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101
2022-10-16 09:32:12,473 Could not get MSA/templates for AA2AR_Nb.AD101: Could not find CIFs in /home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101
Traceback (most recent call last):
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1341, in run
    host_url,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 790, in get_msa_and_templates
    query_seqs_unique[index],
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 158, in mk_template
    obsolete_pdbs_path=None,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/data/templates.py", line 828, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in /home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101
2022-10-16 09:32:12,474 Done

And I have never encountered this error before(I have been using it for a while) Plus, other input files that have been successfully calculated before also failed when I try to re-run it today.

Thanks a lot in advance for reviewing my issue!

**Comment by YoshitakaMo** [comment]
I've never encountered such an issue. Why don't you delete the colabfold_batch directory and reinstall it?

**Comment by TieliangGan** [comment]
Thanks for your kind response! I have tried re-install it just now. However, the problem is still there and the same error is raised.

colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax '/home/Pan_lab/Desktop/inputfile.fasta' /home/Pan_lab/Desktop/ZXD_3
2022-10-17 03:14:28,332 Running colabfold 1.3.0 (cc434cd7e93d9c6034c2fe8e7b92ba4cce3c8268)
2022-10-17 03:14:29,432 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
Downloading alphafold2 weights to /home/Pan_lab/colabfold_batch/colabfold: 100%|
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
Fontconfig error: Cannot load default config file: No such file: (null)
2022-10-17 03:25:47,228 Could not open font file /usr/share/fonts/google-noto-emoji/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.
2022-10-17 03:25:47,613 generated new fontManager
2022-10-17 03:25:49,140 Found 8 citations for tools or databases
2022-10-17 03:25:52,709 Query 1/1: AA2AR_Nb.AD101 (length 534)
COMPLETE: 100%|██████████████████████| 300/300 [elapsed: 00:05 remaining: 00:00]

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat ‘/home/Pan_lab/Desktop/ZXD_3/AA2AR_Nb.AD101_env/templates_101/pdb70_a3m.ffindex’: No such file or directory

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat ‘/home/Pan_lab/Desktop/ZXD_3/AA2AR_Nb.AD101_env/templates_102/pdb70_a3m.ffindex’: No such file or directory
2022-10-17 03:25:58,447 Could not find CIFs in /home/Pan_lab/Desktop/ZXD_3/AA2AR_Nb.AD101_env/templates_101
2022-10-17 03:25:58,448 Could not get MSA/templates for AA2AR_Nb.AD101: Could not find CIFs in /home/Pan_lab/Desktop/ZXD_3/AA2AR_Nb.AD101_env/templates_101
Traceback (most recent call last):
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 1341, in run
    host_url,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 790, in get_msa_and_templates
    query_seqs_unique[index],
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/batch.py", line 158, in mk_template
    obsolete_pdbs_path=None,
  File "/home/Pan_lab/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/data/templates.py", line 828, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in /home/Pan_lab/Desktop/ZXD_3/AA2AR_Nb.AD101_env/templates_101
2022-10-17 03:25:58,449 Done

**Comment by YoshitakaMo** [comment]
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
```
One possible cause is that the downloaded mmCIF files in `/home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101` maybe broken for some reason when it was taken from the Internet. And, the error occurs unless removing the output directory. So try to remove the `/home/Pan_lab/Desktop/ZXD_1` directory and re-run it.

```
And I have never encountered this error before(I have been using it for a while) Plus, other input files that have been successfully calculated before also failed when I try to re-run it today.
```

But, it would be very strange if indeed all your calculations cause a similar error. It is not very likely, but possible that `gzip` or `gunzip` command itself, which decompresses gzip and tar, may be corrupted...?

**Comment by YoshitakaMo** [comment]
Ah, please show me the list of directory of `/home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101` before removing it.

```
$ ls -lt /home/Pan_lab/Desktop/ZXD_1/AA2AR_Nb.AD101_env/templates_101
```

**Comment by TieliangGan** [comment]
![image](https://user-images.githubusercontent.com/98633268/196140752-49edc591-9a13-49d3-baac-395c55baf828.jpeg)

There is only a ffdata file in this directory.

**Comment by TieliangGan** [comment]
well there is only a ffdata file in this directory.

[root@localhost templates_101]# ls
pdb70_cs219.ffdata
[root@localhost templates_101]# ls -lt
total 0
-rw-r--r--. 1 root root 0 Oct 17 05:21 pdb70_cs219.ffdata
[root@localhost templates_101]#

**Comment by TieliangGan** [comment]
I tried to remove and re-run it but it doesn't work. 

Indeed, all of my calculations raise the same error...

**Comment by YoshitakaMo** [comment]
Can you decompress .cif.gz files? For example,

```
$ wget https://files.rcsb.org/download/1ALK.cif.gz
$ gunzip 1ALK.cif.gz
```

**Comment by YoshitakaMo** [comment]
Show me the full output log after removing the output directory if exists:

```
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax '/home/Pan_lab/Desktop/inputfile.fasta' /home/Pan_lab/Desktop/ZXD_3

2022-10-17 19:13:53,348 Running colabfold 1.3.0 (22671664ac2c9dcb30086c3e654414d950ccb297)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-10-17 19:13:55,323 Found 8 citations for tools or databases
2022-10-17 19:13:57,736 Query 1/1: Foobar (length 47)
COMPLETE: 100%|█████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-10-17 19:14:05,481 Sequence 0 found templates: ['3poy_A', '3poy_A', '3qcw_A', '3qcw_A', '4xbm_A', '4xbm_B', '5fm9_A', '5fma_A', '4d90_A', '4d90_B', '4xbm_B', '4d90_A', '4d90_B']
2022-10-17 19:14:05,541 Running model_1
```

**Comment by TieliangGan** [comment]
I do can decompress those files and gunzip works fine. For your second demand, I don't quite understand you. Are you asking for:
[root@localhost Desktop]# colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax '/home/Pan_lab/Desktop/inputfile.fasta'
usage: colabfold_batch [-h] [--stop-at-score STOP_AT_SCORE]
                       [--stop-at-score-below STOP_AT_SCORE_BELOW]
                       [--num-recycle NUM_RECYCLE]
                       [--num-ensemble NUM_ENSEMBLE]
                       [--random-seed RANDOM_SEED] [--num-models {1,2,3,4,5}]
                       [--recompile-padding RECOMPILE_PADDING]
                       [--model-order MODEL_ORDER] [--host-url HOST_URL]
                       [--data DATA]
                       [--msa-mode {MMseqs2 UniRef+Environmental),MMseqs2 (UniRef only,single_sequence}]
                       [--model-type {auto,AlphaFold2-ptm,AlphaFold2-multimer-v1,AlphaFold2-multimer-v2}]
                       [--amber] [--templates]
                       [--custom-template-path CUSTOM_TEMPLATE_PATH] [--env]
                       [--cpu] [--rank {auto,plddt,ptmscore,multimer}]
                       [--pair-mode {unpaired,paired,unpaired+paired}]
                       [--recompile-all-models]
                       [--sort-queries-by {none,length,random}]
                       [--save-single-representations]
                       [--save-pair-representations] [--training]
                       [--max-msa {512:5120,512:1024,256:512,128:256,64:128,32:64,16:32}]
                       [--zip] [--use-gpu-relax]
                       [--overwrite-existing-results]
                       input results
colabfold_batch: error: the following arguments are required: results

or just the rm - rf command?(This does not have an output)
(run the command you wrote above gives exactly the same error)

**Comment by TieliangGan** [comment]
An update: I found that when I run the sequences that do not have a template(those that the msa server cannot find template, it runs normally:

colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax '/home/Pan_lab/Desktop/outputfiles/kinesin.fasta' ./GXY
2022-10-17 07:48:40,038 Running colabfold 1.3.0 (cc434cd7e93d9c6034c2fe8e7b92ba4cce3c8268)
2022-10-17 07:48:41,040 --max-msa can not be used in combination with AlphaFold2-multimer (--max-msa ignored)
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-10-17 07:48:42,786 Found 8 citations for tools or databases
2022-10-17 07:48:46,387 Query 1/1: kinesin (length 594)
COMPLETE: 100%|█████████████████████████| 300/300 [elapsed: 00:01 remaining: 00:00]
2022-10-17 07:48:47,435 Sequence 0 found no templates
2022-10-17 07:48:47,436 Sequence 1 found no templates
COMPLETE: 100%|█████████████████████████| 300/300 [elapsed: 00:00 remaining: 00:00]
2022-10-17 07:48:48,537 Running model_3

**Comment by YoshitakaMo** [comment]
Yes, I wanted to know if the issue occurs when the templates were found or not.
I checked the colabfold.py and found a minimal test for this case. Try the command and check the result:

```
$ mkdir ./testdownload
$ curl -s -L https://api.colabfold.com/template/1ALK_A | tar xzf - -C ./testdownload/
$ ls -l ./testdownload
total 660
-rw-rw-r-- 1 moriwaki moriwaki 672013 Oct 18 00:35 1alk.cif
-rw-rw-r-- 1 moriwaki moriwaki      0 Oct 18 00:35 pdb70_a3m.ffdata
-rw-rw-r-- 1 moriwaki moriwaki      0 Oct 18 00:35 pdb70_a3m.ffindex
```

**Comment by TieliangGan** [comment]
wow I think the problem is here!
The output is as follows:
(And honestly the original environment variable for curl is not this but I don't remember the original address)
[root@localhost Pan_lab]# cd Desktop/
[root@localhost Desktop]# mkdir ./testdownload
[root@localhost Desktop]# curl -s -L https://api.colabfold.com/template/1ALK_A | tar xzf - -C ./testdownload/

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[root@localhost Desktop]# which curl
/home/Pan_lab/Downloads/pymol/bin/curl
[root@localhost Desktop]# cd ./testdownload/
[root@localhost testdownload]# ll
total 0

**Comment by TieliangGan** [comment]
Oh when I move this curl away then the default curl recovered! I think the issue has been solved! Thank you very much! ありがとうございました！
