### ISSUE TITLE
Question: Use roseTTAfold or ESMfold instead of AlphaFold

### ISSUE THREAD

**Issue by ctueting** [YoshitakaMo/localcolabfold#116]
I recently installed localcolabfold and it's working like a charm, thanks for your effort 👍 

I am now curious if one can also use roseTTAfold or the new ESM fold. In the help text, only AlphaFold presets are available.
On the main page, there is the citation for roseTTAfold, so I assume, this is in principle possible.

I searched the other issues, but I don't find an answer to this.

Thx
Christian

**Comment by YoshitakaMo** [comment]
Sorry, my description was not good. This repository is not designed for the installation of RoseTTAFold. I removed it from the main page.

**Comment by ctueting** [comment]
Ah alright. I was already suspecting this, but thanks for clarification!
