### ISSUE TITLE
Increase --num-models?

### ISSUE THREAD

**Issue by FlorianWieser1** [YoshitakaMo/localcolabfold#117]
Dear authors, 
Thank you for implementing this, works like a charm!

I wonder if it is easily possible to increase the number of generated models higher than 5. If so - Which lines of code to tweak?

Thank you in advance!

**Comment by heiidii** [comment]
Any progress on this issue? Would like to generate more than 5 models especially when using dropout.

**Comment by YoshitakaMo** [comment]
How about using `--random-seed` and `--num-seeds`? For example, `--random-seed 42 --num-seeds 3` will generate 15 (5 * 3) models with `--random-seed 42`, `--random-seed 43`,and `--random-seed 44` options. This random seed determines which sequence in the MSA file will be selected as a cluster center, resulting in diverse structure models.

**Comment by FlorianWieser1** [comment]
Ahh.. I had put it into a bash loop and let the random-seed change each iteration. Thank you!
