### ISSUE TITLE
Question: Using local MSA file for structure prediction

### ISSUE THREAD

**Issue by biotech70** [YoshitakaMo/localcolabfold#118]
Hi, based on the content of *Prediction of multiple conformational states by combining sequence clustering with AlphaFold2* paper, I tried to predict the conformations for the target protein using Local-ColabFold. For this purpose, I need to use clustered MSA files. Is it possible to use a local MSA file to predication the model using Local-ColabFold?

**Comment by YoshitakaMo** [comment]
You can specify your custom MSA file in `inputfile`. For example,

```bash
colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax inputfile outputdir/

**Comment by biotech70** [comment]
thanks
