### ISSUE TITLE
colabfold_batch is too slow.

### ISSUE THREAD

**Issue by Yu1065** [YoshitakaMo/localcolabfold#121]
Dear authors

Thanks for this useful software.
I recently got a new PC (corei9 13900k and RTX3080 ). Compared to my previous PC (corei5 12400 and RTX3050), the calculation speed on the GPU is about 10 times slower.
What could be the cause of this?

I'm using WSL2 (Ubuntu22.04) on windows.

Thank you.

**Comment by YoshitakaMo** [comment]
Please complete the issue template to find the cause.
> Compared to my previous PC (corei5 12400 and RTX3050), the calculation speed on the GPU is about 10 times slower.
Does `nvidia-smi` return the information of your GPU?

**Comment by Yu1065** [comment]
Thank you for your response. Checking the Windows task manager, we confirmed that GPU utilization increased to 100%.

Here are the details.


**What is your question?**

Prediction by RTX3080 is too slow compared to RTX3050.


**Computational environment**
PC1
OS: Windows11 & WSL2 (Ubuntu22.04)
GPU: RTX3080
CUDA version: 11.7
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.02    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+



PC2
OS: Windows11 & WSL2 (Ubuntu20.04)
GPU: RTX3050
CUDA version: 11.6
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+



**To Reproduce**
input file: 132 residues of amino acids in a fasta file
command: colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax --num-models 1 input_file output_dir

result of PC1:
2022-12-02 23:27:08,847 Found 8 citations for tools or databases
2022-12-02 23:27:30,690 Query 1/1: test (length 132)
COMPLETE: 100%|██████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-12-02 23:27:34,341 Sequence 0 found templates: ['1iuq_A', '1k30_A']
2022-12-02 23:27:34,358 Running model_3
2022-12-02 23:42:04,838 model_3 took 869.4s (3 recycles) with pLDDT 94.2 and ptmscore 0.763
2022-12-03 00:12:23,090 Relaxation took 1258.8s
2022-12-03 00:12:23,091 reranking models by plddt
2022-12-03 00:12:23,449 Done


result of PC2:
2022-12-02 23:31:39,068 Found 8 citations for tools or databases
2022-12-02 23:31:42,387 Query 1/1: test (length 132)
COMPLETE: 100%|██████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
tar: pdb70_a3m.ffdata: time stamp 2022-12-02 23:31:47 is 2.072918125 s in the future
tar: pdb70_a3m.ffindex: time stamp 2022-12-02 23:31:47 is 2.07277204 s in the future
tar: 1iuq.cif: time stamp 2022-12-02 23:31:47 is 2.062931879 s in the future
tar: 1k30.cif: time stamp 2022-12-02 23:31:47 is 2.061472278 s in the future
2022-12-02 23:31:46,003 Sequence 0 found templates: ['1iuq_A', '1k30_A']
2022-12-02 23:31:46,026 Running model_3
2022-12-02 23:32:47,343 model_3 took 59.8s (3 recycles) with pLDDT 94.1 and ptmscore 0.766
2022-12-02 23:33:18,952 Relaxation took 26.3s
2022-12-02 23:33:18,952 reranking models by plddt
2022-12-02 23:33:19,428 Done

**Comment by YoshitakaMo** [comment]
> Checking the Windows task manager, we confirmed that GPU utilization increased to 100%.

It's very strange. Does `nvidia-smi` show the colabfold_batch process when it's running?
If you run some calculations that can be accelerated by GPU, is it accelerated normally on PC1?

Since I don't have Windows11 ( and WSL Ubuntu 22.04), I'm having difficulty identifying the cause.

**Comment by Yu1065** [comment]
>Does nvidia-smi show the colabfold_batch process when it's running?
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
|  0%   35C    P2   138W / 320W |    872MiB / 10240MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        38      G   /Xwayland                       N/A      |
|    0   N/A  N/A      1419      C   /python3.7                      N/A      |
+-----------------------------------------------------------------------------+

We have tried several programs that worked with tensorflow and they all accelerated normally.
In addition, We tried changing the Ubuntu version and the cuda version, but did not see any improvement.

During the colabfold_batch process on PC1, 20gb ram and less than 1gb VRAM were used　(on PC2, it is 12gb RAM and 2gb VRAM).
I will look into the cause of this difference.

Thank you.
