### ISSUE TITLE
Using CPU instead of GPU

### ISSUE THREAD

**Issue by HMPNK** [YoshitakaMo/localcolabfold#122]
Let me thank you first for your work on local colabfold, I messed around with local installation of alphafold2 and found this the best solution so far.

I found just one issue, on computers with GPU the switch "--cpu" is not switching to CPU mode. The GPU is always prefered. There are cases when a user might want to use CPU mode, because the GPU memory is not sufficient.

I found the following solution to hide the CUDA devices, before running colabfold_batch:

**export CUDA_VISIBLE_DEVICES=""**

Hope this might help other users!

**Comment by boyinthebigcity** [comment]
I'm still getting the following error message despite hiding the CUDA devices, whether directly in terminal or in ~/.zshrc:
**_colabfold_batch: error: unrecognized arguments: --cpu_**

Any idea how to get around this? For reference, I'm running on macOS Ventura

**Comment by YoshitakaMo** [comment]
Recently `--cpu` flag has been obsoleted. Please remove the flag from `colabfold_batch/bin/colabfold_batch` or try a new installation after removing the existing `colabfold_batch` directory.

**Comment by pedroleao2** [comment]
One related question...
Now that the --cpu flag was removed, there is an alternative way on how I can control the number of cores/cpus used by the program while running?

**Comment by j3mdamas** [comment]
I have the same question as @pedroleao2
Is there an alternative @YoshitakaMo?

**Comment by YoshitakaMo** [comment]
@pedroleao2 @j3mdamas 

That is odd. In my environment, as shown by HMPNK, if I run `export CUDA_VISIBLE_DEVICES=""` first and then run `colabfold_batch` command, it works on the CPU.

```bash:run_colabfold.sh
#!/bin/bash

export CUDA_VISIBLE_DEVICES=""
colabfold_batch <flags> input outputdir
```

```
2023-06-23 17:17:57,709 Running colabfold 1.5.2 (affc6e0e89ee723795ab009f51f2600d843dafb0)
2023-06-23 17:17:57.735973: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-06-23 17:17:57,736 WARNING: no GPU detected, will be using CPU
2023-06-23 17:17:58.575789: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-06-23 17:17:58,927 Found 2 citations for tools or databases
```

**Comment by j3mdamas** [comment]
@YoshitakaMo sorry, maybe I should have been clearer.
I am able to run colabfold_batch on CPUs (like you demonstrate), but I am not able to control the amount of cores/threads it's using: right now, it's taking everything by default. I think it would be an useful feature to be released. Thank you.

**Comment by pedroleao2** [comment]
Yes, that's also what I would like to find out. =)

**Comment by j3mdamas** [comment]
I guess this have been a better issue directly on the ColabFold repository, but since the focus I had was on local build in an HPC system and since this issue was already open, I followed up on it.

My understanding from [this issue](https://github.com/google/jax/issues/1539) is that it maybe be an implementation missing in Jax, which is used in the background of colabfold_batch. Apparently the solution is to use something else to control the CPU access to the colabfold_batch process, but I was hoping there was a native flag to control it directly. I guess I'll pursue that path then.
