### ISSUE TITLE
Question: Installation problem

### ISSUE THREAD

**Issue by Neverland999** [YoshitakaMo/localcolabfold#123]
Dear authors

I recently installed the LocalColabFold in the Linux system based on the Ubuntu PC operating system, but something was wrong when I ran " bash install_colabbatch_linux.sh".  It showed "Solving environment: failed with initial frozen solve. Retrying with flexible solve." in the terminal window. Then I checked the  installed "colabfold_batch" directory, and there were two folders (colabfold-conda, conda) in the directory. How could I install it successfully?

**Computational environment**
 - OS: Ubuntu 11.3.0

Thank you.

**Comment by YoshitakaMo** [comment]
> Ubuntu 11.3.0

It's very old. Is it correct?

> but something was wrong when I ran " bash install_colabbatch_linux.sh". It showed "Solving environment: failed with initial frozen solve. Retrying with flexible solve." in the terminal window.

Let me show the complete log file when running `bash install_colabbatch_linux.sh`.
