### ISSUE TITLE
Large batch of jobs

### ISSUE THREAD

**Issue by hz424** [YoshitakaMo/localcolabfold#13]
I am trying to run this on HPC for a large batch of jobs. Submitting jobs to mmseqs2 server seems to be the step slowing down for large batch. Is it easy to generate the MSA using local mmseqs2 for the same pickle format? Thanks!!

**Comment by matrs** [comment]
> Sorry for the late reply. I'm trying to figure out how to do MSA generation using local mmseqs2 on my PC. The way is described here (https://colabfold.mmseqs.com/). If the method is established, I will introduce it here and consider incorporating it into localcolabfold to produce a compatible pkl file. However, my PC doesn't have as much RAM as a web server (~1TB), so the generation should be inevitably slower.

How large do you expect this pkl file to be?
