### ISSUE TITLE
Question: a separate location for the dir with AF2 weights

### ISSUE THREAD

**Issue by Khalimat** [YoshitakaMo/localcolabfold#134]
Hey! Thank you for the repo, it makes my PhD life much better. 

I am wondering if I could specify a dir with AF2 weights and separate it from the installation dir? I am working on HPS, so we have separate locations for DBs and software, and we are extremely cautious about taking extra space in the software directory. 

To be more precise, I have a directory with software (`/x_name/software`) and a directory with DBs (`/x_name/DBs`), so I would like to save AF2 weights in `/x_name/DBs/colabfold_batch/colabfold/params`, but have everything else (`/x_name/software/colabfold_batch/colabfold-conda` and `/x_name/software/colabfold_batch/conda`) in `/x_name/software`.

**Comment by YoshitakaMo** [comment]
The default params directory is specified in line 12 of `colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold`. In this repo, I modified the value from `~/.cache` directory of each user for cluster computers. You can modify the value to `/x_name/DBs/colabfold_batch/colabfold` and remove `__pycache__` directory on `colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold` for your purpose.

See also https://github.com/sokrypton/ColabFold/blob/b4c1bc7cf89bc0bd577c5a9d3c1f7bedc1f74152/colabfold/download.py#L12

**Comment by Khalimat** [comment]
Thank you so much!
