### ISSUE TITLE
Question: Generating model image with color by pLDDT value

### ISSUE THREAD

**Issue by bfjia** [YoshitakaMo/localcolabfold#137]
**What is your question?**
Is it possible to use localcolabfold to generate a protein model image and/or PDB file with color by pLDDT value similar to what you get on the google colabfold?
thank you!

**Comment by YoshitakaMo** [comment]
pLDDT values are embedded in the b-factor columns of the output pdb files. Thus, you can color them using these commands;

For PyMOL,
```
color 0x0053D6, (object_name) and b < 100
color 0x65CBF3, (object_name) and b < 90
color 0xFFDB13, (object_name) and b < 70
color 0xFF7D45, (object_name) and b < 50
```

<img width="858" alt="68747470733a2f2f71696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f302f3232343332372f35353436653631622d363036642d363463372d616133632d6539646361303832316633612e706e67" src="https://user-images.githubusercontent.com/16487484/221360666-fb3ab08f-1bae-4a22-9298-b34a3505efb1.png">

For UCSF Chimera,

```
color #0053D6 @/bfactor<100
color #65CBF3 @/bfactor<90
color #FFDB13 @/bfactor<70
color #FF7D45 @/bfactor<50
```

<img width="1151" alt="68747470733a2f2f71696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f302f3232343332372f64343566323833392d336339612d353133332d356261302d3461303531633265653533372e706e67" src="https://user-images.githubusercontent.com/16487484/221360625-6f8cdcdb-5f0f-493c-bed7-0d93cd3d2635.png">

For UCSF ChimeraX, 

```
color @@bfactor<100 #0053D6
color @@bfactor<90 #65CBF3
color @@bfactor<70 #FFDB13
color @@bfactor<50 #FF7D45
```

<img width="1071" alt="68747470733a2f2f71696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f302f3232343332372f65303462383936612d623734612d363563312d316630662d6163613462633863373233332e706e67" src="https://user-images.githubusercontent.com/16487484/221360637-df0b3b7d-a809-4c2b-8663-696f11ec0bc2.png">

**Comment by bfjia** [comment]
thank you
