### ISSUE TITLE
Install issues and GPU not detected on fresh install

### ISSUE THREAD

**Issue by scg34** [YoshitakaMo/localcolabfold#138]
**What is your question?**
I've just updated colabfold to v 1.5.2 by doing a fresh install. I noticed a couple of issued with the install scripts and, once overcome, am still having some issue with my GPU not being identified. Previous colabfold install (1.3) worked as expected.

**Computational environment**
 - OS: Ubuntu 20.04.5 LTS
 - CUDA version: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jul_14_19:41:19_PDT_2021
Cuda compilation tools, release 11.4, V11.4.100
Build cuda_11.4.r11.4/compiler.30188945_0

 nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1080 Ti (UUID: GPU-d41cf7ec-481a-17c6-2f39-81ebbb68809b)
GPU 1: NVIDIA GeForce GTX 1080 Ti (UUID: GPU-71385f22-4d97-d7c8-fc1a-a2a3d4815680)

**To Reproduce**

Issue 1:
For the install, just do a fresh install in a new directory. The install script downloads the update_linux script and gives it executable permissions (lines 21-22) but does not actually execute it.
==> Fixed by running "bash update_linux.sh" after the install scripT

Issue 2:
On my ubuntu machine the install script and update script tried to install all the python packages under the local user's home directory.
==> Fixed by appending "-t ${COLABFOLDDIR}/colabfold-conda/lib/python3.8/site-packages" to all pip install commands in the install and update scripts

Issue 3:
Once installed successfully, I can run colabfold_batch but doesn't recognise the GPU:
2023-03-01 17:06:51,883 Running colabfold 1.5.2 (7d5e42c00829e12e38bd8965767302367cf90cd2)
2023-03-01 17:06:51,993 WARNING: no GPU detected, will be using CPU
==> Issue still outstanding

Any help would be appreciated! Thanks, Stephen

**Comment by KYQiu21** [comment]
same problem. any updates?

**Comment by scg34** [comment]
Sadly no, not yet.

I tried re-installing my NVidia drivers and updating CUDA and CUDNN to the latest 11.*/8.* versions.

:~> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

:~> cat /usr/include/cudnn_version.h
...
#define CUDNN_VERSION_H_

#define CUDNN_MAJOR 8
#define CUDNN_MINOR 8
#define CUDNN_PATCHLEVEL 0
...

:~> nvidia-smi
Mon Mar  6 11:49:30 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 23%   26C    P8    14W / 250W |   2082MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:02:00.0 Off |                  N/A |
| 23%   22C    P8     7W / 250W |    146MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

This all works with a non-docker install of AlphaFold2 (basically followed the instructions of https://github.com/PasqM/alphafold_non_docker but used "pip install --upgrade "jax==0.3.25" "jax[cuda]==0.3.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html" for the jax cuda install)

nvidia-smi shows 99% GPU usage of one of my GPUs when doing the AF2 prediction, so I'm happy the GPU and CUDA libraries are working fine, there's just something messed up with the colabfold install.

Any suggestions on how to further troubleshoot would be very welcome!

Thanks,

Stephen
