### ISSUE TITLE
Precomputedのバグ？

### ISSUE THREAD

**Issue by sotanengel** [YoshitakaMo/localcolabfold#14]
# バグの内容
## 実行環境

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

## 実行コマンド

```
colabfold-conda/bin/python3.7 runner_af2advanced.py \
--input hoge.fasta \
--output_dir hoge \
--max_recycle 6 \
--msa_method single_sequence \
--num_relax Top5
```

## エラー内容

```
Traceback (most recent call last):
  File "runner_af2advanced.py", line 161, in <module>
    pair_mode, pair_cov, pair_qid, precomputed=precomputed, TMP_DIR=TMP_DIR)
NameError: name 'precomputed' is not defined
```

# 問題の推測
msa_methodの引数をprecomputed以外にした際に、precomputedを変数として定義する部分が存在しないので161行目で変数がないというエラーになるのではないでしょうか？
https://github.com/YoshitakaMo/localcolabfold/blob/34c1035e549a79b70a9c716e64511d24b6121d75/runner_af2advanced.py#L141-L161

# 解決方法
以下のようにelseを追加して、precomputedを定義する部分を作成してはいかがでしょうか？
https://github.com/YoshitakaMo/localcolabfold/pull/15/commits/8b2f2fffee6da6c9f03529935f0ccbad111f35dd

**Comment by YoshitakaMo** [comment]
Merged it. Thank you for your PR😀
