### ISSUE TITLE
Question:  Segmentation fault

### ISSUE THREAD

**Issue by lh12565** [YoshitakaMo/localcolabfold#148]
**What is your question?**
Hi, when I run localcolabfold, there is an error.

**Computational environment**
 - OS: CentOS 7
 - CUDA version if Linux:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

**To Reproduce**

1. run:
```
colabfold_batch  --model-type alphafold2_multimer_v3 ifitm3_ps1_notch.fasta out
```
2. error:
```
2023-04-07 02:28:13,869 Running colabfold 1.5.2

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can 
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2023-04-07 02:28:23,012 Running on GPU
2023-04-07 02:28:24,282 Found 4 citations for tools or databases
2023-04-07 02:28:24,283 Query 1/1: ps1 (length 729)
Segmentation fault
```

**Expected behavior**
I want to predict a complex (three sequence of my fasta) using localcolabfold.
Thanks!

**Comment by YoshitakaMo** [comment]
- Which GPU model do you use? (RTX 3090, RTX3060, etc...)
- What is your gcc version? `gcc --version`
