### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by juankaamez** [YoshitakaMo/localcolabfold#150]
**How much disk space does localcolabfold need after installation?**
How much disk space does localcolabfold need to run locally? Does it download databases and if so, how much space do they need and which ones are the?
**Computational environment**
 - OS: [Windows10 & WSL2]
 - CUDA version if Linux (Show the output of `/usr/local/cuda/bin/nvcc --version`.)

**Comment by YoshitakaMo** [comment]
Localcolabfold requires only ~15GB. The databases necessary for AlphaFold2 such as BFD, Uniref90, and etc. are not required.

**Comment by YoshitakaMo** [comment]
Localcolabfold requires Internet connection during its MSA search if the input is a fasta format or use `--templates` argument. It is recommended that the device be connected to a network.

**Comment by juankaamez** [comment]
Could the MSA search be performed using a server connected to several local clients and if so, what would that server have to download?
I would like to know if those databases could be downloaded in areas with restricted internet access but which could have a server, to understand better where is the MSA search performed, Google servers maybe? And also if there are any restrictions on the amount of MSA searches that you can perform in thoses servers.
Thanks a lot in advance Yhositaka for your great help and wisdom here!

**Comment by terachi2022** [comment]
I have a similar question,
I would like to link localcolabfold and MMseqs-app to keep the array out of the outside world. (MMseqs-app has the colab api, so maybe the linkage could work? )

If possible, it would be helpful if you could tell me the part of the configuration that needs to be changed (where the access to the MSA Server is set in google colab).
https://github.com/soedinglab/MMseqs2-App

**Comment by gwirn** [comment]
@juankaamez The MSA is generated using the MMSeqs2 server. To run this locally see [here](https://github.com/sokrypton/ColabFold/blob/main/README.md#generating-msas-for-large-scale-structurecomplex-predictions) and [here](https://github.com/soedinglab/MMseqs2#installation). There you will get the databases and installation instructions you need to compute the MSA on your own. And as stated when running colabfold "You can 
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`"
