### ISSUE TITLE
Question: Unsuccessful installation

### ISSUE THREAD

**Issue by Nythm99** [YoshitakaMo/localcolabfold#154]
**What is your question?**

Unsuccessful installation

**To Reproduce**

bash install_colabbatch_linux.sh 

**Expected behavior**
Collecting colabfold[alphafold-minus-jax]@ git+https://github.com/sokrypton/ColabFold
  Cloning https://github.com/sokrypton/ColabFold to /tmp/pip-install-l8izc3n9/colabfold_d526430266714ed89c9ec07e124ee2a5
  Running command git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold /tmp/pip-install-l8izc3n9/colabfold_d526430266714ed89c9ec07e124ee2a5
  fatal: unable to access 'https://github.com/sokrypton/ColabFold/': Empty reply from server
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold /tmp/pip-install-l8izc3n9/colabfold_d526430266714ed89c9ec07e124ee2a5 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold /tmp/pip-install-l8izc3n9/colabfold_d526430266714ed89c9ec07e124ee2a5 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Collecting jaxlib==0.3.25+cuda11.cudnn82
  Using cached https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn82-cp310-cp310-manylinux2014_x86_64.whl (154.5 MB)
Collecting scipy>=1.5 (from jaxlib==0.3.25+cuda11.cudnn82)
  Using cached scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
Requirement already satisfied: numpy>=1.20 in ./colabfold-conda/lib/python3.10/site-packages (from jaxlib==0.3.25+cuda11.cudnn82) (1.24.3)
Installing collected packages: scipy, jaxlib
Successfully installed jaxlib-0.3.25+cuda11.cudnn82 scipy-1.10.1
Collecting jax==0.3.25
  Using cached jax-0.3.25-py3-none-any.whl
Collecting chex==0.1.6
  Using cached chex-0.1.6-py3-none-any.whl (87 kB)
Collecting biopython==1.79
  Using cached biopython-1.79-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
Requirement already satisfied: numpy>=1.20 in ./colabfold-conda/lib/python3.10/site-packages (from jax==0.3.25) (1.24.3)
Collecting opt-einsum (from jax==0.3.25)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: scipy>=1.5 in ./colabfold-conda/lib/python3.10/site-packages (from jax==0.3.25) (1.10.1)
Collecting typing-extensions (from jax==0.3.25)
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting absl-py>=0.9.0 (from chex==0.1.6)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting dm-tree>=0.1.5 (from chex==0.1.6)
  Using cached dm_tree-0.1.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Requirement already satisfied: jaxlib>=0.1.37 in ./colabfold-conda/lib/python3.10/site-packages (from chex==0.1.6) (0.3.25+cuda11.cudnn82)
Collecting toolz>=0.9.0 (from chex==0.1.6)
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Installing collected packages: dm-tree, typing-extensions, toolz, opt-einsum, biopython, absl-py, jax, chex
Successfully installed absl-py-1.4.0 biopython-1.79 chex-0.1.6 dm-tree-0.1.8 jax-0.3.25 opt-einsum-3.3.0 toolz-0.12.0 typing-extensions-4.5.0
install_colabbatch_linux.sh: line 33: cd: /home/Public/software/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold: No such file or directory
sed: can't read plot.py: No such file or directory
sed: can't read download.py: No such file or directory
/home/Public/software/colabfold/localcolabfold/colabfold-conda/bin/python3.10: Error while finding module specification for 'colabfold.download' (ModuleNotFoundError: No module named 'colabfold')
Download of alphafold2 weights finished.
-----------------------------------------
Installation of colabfold_batch finished.
Add /home/Public/software/colabfold/localcolabfold/colabfold-conda/bin to your environment variable PATH to run 'colabfold_batch'.
i.e. For Bash, export PATH="/home/Public/software/colabfold/localcolabfold/colabfold-conda/bin:$PATH"
For more details, please type 'colabfold_batch --help'.

**Comment by Nythm99** [comment]
solved:
add .git to the  https://github.com/sokrypton/ColabFold and make it into  https://github.com/sokrypton/ColabFold.git in the  install_colabbatch_linux.sh file and  the related files

**Comment by lijianghui01** [comment]
Collecting colabfold@ git+https://github.com/sokrypton/ColabFold.git (from colabfold[alphafold-minus-jax]@ git+https://github.com/sokrypton/ColabFold.git)
  Cloning https://github.com/sokrypton/ColabFold.git to /tmp/pip-install-xy8jvdph/colabfold_0b9c8151e2ae4554b96e3aacd15d0610
  Running command git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold.git /tmp/pip-install-xy8jvdph/colabfold_0b9c8151e2ae4554b96e3aacd15d0610
 'https://github.com/sokrypton/ColabFold.git/'：Failed to connect to github.com port 443 after 127311 ms: Could not connect to server
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold.git /tmp/pip-install-xy8jvdph/colabfold_0b9c8151e2ae4554b96e3aacd15d0610 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/sokrypton/ColabFold.git /tmp/pip-install-xy8jvdph/colabfold_0b9c8151e2ae4554b96e3aacd15d0610 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I encountered the same issue, and even after adding git to the install.sh script, the error still persists.
