### ISSUE TITLE
How to specify a custom MSA.

### ISSUE THREAD

**Issue by PabloGalazDavison** [YoshitakaMo/localcolabfold#157]
Dear all,

Thanks for this tool, its development has really made AF2 accessible for everyone. I have a question regarding localcolabfold. I'm trying to run a homodimer sequence, and it does not retrieve a MSA from the MMSEQS server. I have a multifasta with my sequences, separated by a ":", which came from an MSA of the sequences separated by a colon. Then, I wonder, can I use this initial fasta MSA as a custom MSA for predictions?
On theoretical grounds, it is a good MSA, 3.8k sequences with members of different species of this transcription factor.
Thanks in advance,
Pablo

**Comment by YoshitakaMo** [comment]
Sorry for the late reply.
You can simply input your a3m file as follows: `colabfold_batch <options> your_msa.a3m output_dir`

Here is an example of the a3m file for predicting homo-**hexamer** for a protein of length **62**.

```
#62 6
>101
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR
>101
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR
>A0A1M5AEK1
PIYHIEMMEGRTPEQKRKLVEAVTRVSVDILGGSPEAVHVLIHEIPRDNWATGGQLWSERK-
>A0A7C4BER2
PVVTIEMWEGRTPEQKKALVEAVTSAVAGAIGCPPEAVEVIIHEVPKVNWGIGGQIASE---
>UPI00178343E4
PFVHVRITRdGTSQAQKRQLVREITDTLERVLGKQPDLTHIVIDEIDTDNWGHGGELVTERR-
>A0A429EDM9
PMINVSMFPGRTAEQKQALVREVTDAFVRTCGGNPEGVWVTINEIPAEHWASGGTLFSER--
>....
...
```

The `62 6` in the first line starting with `#` are the length and the number of *n*-mer.
The following sequence information starting with `>101` is the amino acid sequence to be predicted.
The next `>101` and the sequences `>A0A1M5AEK1, >A0A7C4BER2, ...` are the MSA (a3m format) that you want to use.

For a hetero-multimer prediction, the format is slightly different.

```
#10,5	2,2
>101	102
AAAAAAAAAABBBBB
>foo1      bar1
AAAAAAACAABBBDB
>foo2      bar2
AAcAAAAAAAABbBBBB
>foo3      bar3
AAAAAAADAABBBEB
>101
AAAAAAAAAA-----
>foo1
AAAAAAACAA-----
>MSA for the sequence 101 with gaps
...
...
>102
----------BBBBB
>bar1
----------BBBDB
>bar2
----------BbBBBB
>MSA for the sequence 102 with gaps
...
...
```

**Comment by PabloGalazDavison** [comment]
Thanks for the very complete answer!

**Comment by fglaser** [comment]
Hi, 
Could you please detail a bit more about how exactly the hetero multimer custom msa format should be?

I mean just merging the two a3m and changing the lines
#10,5	2,2
>101	102 (before the first alignmetn)
..
...
and for the second heteromer 
>102 (first of the second alignment)
....

Does not work for me, I am surely doing some trivial mistake.

Thanks a lot,
Fabian
