### ISSUE TITLE
tag for 1.5.2

### ISSUE THREAD

**Issue by lyskov** [YoshitakaMo/localcolabfold#167]
Would it be possible to tag version `1.5.2`? Thanks,

**Comment by YoshitakaMo** [comment]
Sorry for the delay, I've just released v1.5.2.
However, the version tag has little meaning. If you plan to describe the version for your paper, we recommend that you use the version or hash of the ColabFold one. This ColabFold version and hash number are written at the beginning of the localcolabfold output log.

**Comment by lyskov** [comment]
Great, - thank you for taking care of this! 

The primary reason I raised this is so I can reliably install _same_ version of colabfold in container. Ie my current code is trying to checkout particular version of localcolabfold installer and run it, - will that work as expected (ie install particular (and fixed) version of colabfold)?
Thanks,
