### ISSUE TITLE
Different results from ColabFold and localcolabfold

### ISSUE THREAD

**Issue by jongseo-park** [YoshitakaMo/localcolabfold#171]
Hi,

I have a question about structure prediction.

When I run the structure modeling using localcolabfold or colabfold (colab version of sokrypton),

in some cases, the results were different. 

I performed multimer modeling (two molecules), 

and the i_pTM values were >0.8 or <0.5 in the case of colabfold or localcolabfold, respectively.

I set all the parameters for modeling such as template, recycle, msa mode, etc. to be as identical as possible.

What else can I check for ?

Sincerely,
Jongseo

**Computational environment**

 - OS: Ubuntu 22.04
 - CUDA version: 12.3

**Comment by 0kd** [comment]
Hi, I'm facing the same issue. How did you resolve this issue?
