### ISSUE TITLE
Question: I can't seem to use custom templates with local colabfold. 

### ISSUE THREAD

**Issue by jdrohan356** [YoshitakaMo/localcolabfold#177]
----

**What is your installation issue?**

So I have been trying to setup my local colabfold environment to run custom templates using the --custom-templates-path flag. I followed the advice on this github repo and have managed to fix all the errors based on the previous issues posted. However now that I have gotten past the errors, I still can't get the templates to work properly. I know that if the templates are used it should print out something like, "Sequence 0 found templates [XXXX_Y.pdb ...]". When I use the --templates flag I get  a list of templates being used by colabfold, but when I use a custom template directory the same output does not appear. I even put the templates found by the --templates flag into my custom template directory and still no templates were used. Even though none of the templates are used, the prediction still proceeds as normal so I don't know why the templates are being ignored.  

**Computational environment**

 - OS: Ubuntu 20.04.3 LTS
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

**To Reproduce**
As an example I used this fasta sequence as an input - QVQLQESGPGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKGLEWLGMIWGDGNTDYN
SALKSRLSISKDNSKSQVFLKMNSLHTDDTARYYCARERDYRLDYWGQGTTVTVSS:DIV
LTQSPASLSASVGETVTITCRASGNIHNYLAWYQQKQGKSPQLLVYYTTTLADGVPSRFS
GSGSGTQYSLKINSLQPDDFGSYYCQHFWSTPTFGGGTKLEIK

with --templates flag: 
colabfold_batch sample.fasta output.fasta --templates

with --custom-template-path: 
colabfold_batch sample.fasta output.fasta --custom-template-path /path/to/dir

When run with --templates flag I get: 
Sequence 0 found templates: ['4tsb_H', '4tsa_H', '4tsc_H', '7chs_H', '7k8n_A', '7mjk_D', '6xc7_C', '7kn6_H', '6xc4_X', '7d0c_G', '7mjl_H', '7k8m_A', '7kn7_H', '7qf0_H', '7np1_I', '7e3b_B', '6ieb_E', '7sts_A', '6ieb_H', '7sts_H']
2023-09-25 14:02:43,022 
Sequence 1 found templates: ['1a7o_L', '6dzl_J', '1dvf_A', '1kir_A', '7upx_L', '1g7i_A', '1a7r_L', '4kq3_L', '1g7j_A', '5ggt_L', '1g7l_A', '4jr9_L', '4nry_B', '4nrx_B', '6ea7_R', '4liq_L', '6ea7_N', '4ps4_L', '4nrx_E', '4nrx_L']

So then I created a custom template directory with templates found above. 
For example I put the pdb file for 7sts.pdb chain A into the template directory

Then ran it again with the --custom-template-path flag. No templates were used even though 7sts_A was used when the --templates flag was on. 

**Expected behavior**

I had other templates in the custom template directory, many of which were probably not great templates. However I at least expected to see templates used by the --templates be re-used when put into the custom template directory. How many templates should I put into the custom template directory before it should find hits. I started by putting 100 templates and predicting 150 sequences that had average sequence identity of 70% to the templates. None of these predictions used templates so I am not sure how to get them to be used.

**Comment by jdrohan356** [comment]
Ok I realized that you still need to use the --templates flag when working with custom templates. However even when I turned that on I am still getting "Sequence x found no templates" for both chains. Even though my template directory is just three templates that are found when using the --templates flag.

**Comment by lonelyhwy** [comment]
Has this issue been solved?
