### ISSUE TITLE
some basic questions on how to run localcolabfold

### ISSUE THREAD

**Issue by jflucier** [YoshitakaMo/localcolabfold#181]
Hi,

I have looked iton issues and documatation of localcolabfold and colabfold and could not pinpoint the answers to my question. I have run alphafold2 in previous analysis. I am trying to run using prexisting pdbs as template for multimer fold.

1 - When I run colabfold_batch -h, I see option --data, is this the same as alphafold parameter --data_dir ? I have already the alphafold database installed on cluster. In colabfold documentation it is wrtitten to download colabfold database using this command: `./setup_databases.sh /path/to/db_folder`. Do I need to do this or colabfold db and alphafold db are the same?

2 - for the parameter --msa-mode, what do you recommend? mmseqs2_uniref_env?

3 - Do you have any other recommendation for parameters? I am running on a cluster with the following node specification: 40 cores, 186G RAM, 4 x NVidia V100SXM2 (16G memory), connected via NVLink. I intend to use 8 cores, 40G ram and 1 gpu unit.

4 - Last question: The pdb I have downloaded are 2 proteins, 1 is only partially modelled (a signle important protein domain https://www.rcsb.org/structure/6cvz) and the other is already available in trimer (https://www.rcsb.org/structure/2HIK). As a test, I am trying to fold a dimer of 6cvz with the trimer of 2HIK. How will this information by passed in the folding? In the input fasta, do I specifiy the following way:
>test_complex
6cvz_seq:6cvz_seq:2HIK_seq:2HIK_seq:2HIK_seq

as of now (untested), my command would look like this:

```
#!/bin/bash

#SBATCH --job-name=rfwd3_alphafold
#SBATCH -D /home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_out
#SBATCH -o /home/jflucier/projects/def-marechal/analysis/20230922_fold/rfwd3_out/slurm-%A_%a.out
#SBATCH --account=def-marechal
#SBATCH --time=08:00:00
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=20G

source /home/jflucier/alphafold_env/bin/activate
module load mmseqs2/14-7e284

export TF_FORCE_UNIFIED_MEMORY="1"
export XLA_PYTHON_CLIENT_MEM_FRACTION="4.0"
export XLA_PYTHON_CLIENT_ALLOCATOR="platform"
export TF_FORCE_GPU_ALLOW_GROWTH="true"

colabfold_batch \
--num-models 3 \
--use-gpu-relax \
--templates --custom-template-path /path/to/dir \
--msa-mode mmseqs2_uniref_env \
--model-type alphafold2_multimer_v3 \
/path/to/fasta \
/path/to/output
```

Thanks alot in advance for your help,
JF

**Comment by jflucier** [comment]
Thanks for the quick answer. Just listen at video tutorial link and alot is explained in this. Thanks!

The compute nodes on my cluster dont have internet access. Based on your answer (if I unserstand well), I will need to install my own colabfold db server since db file between colabfold and alphafold are not the same.

thanks again alot for your help,
JF

**Comment by YoshitakaMo** [comment]
> The compute nodes on my cluster dont have internet access. Based on your answer (if I unserstand well), I will need to install my own colabfold db server since db file between colabfold and alphafold are not the same.

A hack to circumvent this issue is that once running `colabfold_batch` on the login/gateway node which has Internet access to obtain MSA and templates in advance. In this case, it is not necessary to have a GPU in the login node.
`colabfold_batch` first uses CPU to obtain the MSA (and templates) from the Internet, and then uses the GPU to predict the structure from the MSA( and templates).

The key here is that if the MSA and templates are already stored in the specified output directory, `colabfold_batch` will skip the reacquisition.

To take advantage of this, use `colabfold_batch` on the login node to retrieve the MSA and templates, and when it starts to predict the structure, press Ctrl-C to abort the process.
Then, run `colabfold_batch` on the compute node with GPU and you can perform the structure prediction without internet.

Indeed, since such cases are common, it would be convenient for users to have an option to retrieve only MSA and templates, but this has not been implemented yet.

**Comment by jflucier** [comment]
ok thanks so much for explanation. 

I will be running this in a wider context (high-throughput). The db setup is invitable in this context. All steps need to be scripted and run on compute nodes. I will however keep your solution in mind for my test while all this db data is downloading. 

Indeed a script that only download to complement alphafold db would be realy usefull.

Thank again for your precious help.

**Comment by Tttgb** [comment]
> > The compute nodes on my cluster dont have internet access. Based on your answer (if I unserstand well), I will need to install my own colabfold db server since db file between colabfold and alphafold are not the same.
> 
> A hack to circumvent this issue is that running `colabfold_batch` on the login/gateway node which has Internet access to obtain MSA and templates in advance. In this case, it is not necessary to have a GPU in the login node. `colabfold_batch` first uses CPU to obtain the MSA (and templates) from the Internet, and then uses the GPU to predict the structure from the MSA( and templates).
> 
> The key here is that if the MSA and templates are already stored in the specified output directory, `colabfold_batch` will skip the reacquisition.
> 
> To take advantage of this, use `colabfold_batch` on the login node to retrieve the MSA and templates, and when it starts to predict the structure, press Ctrl-C to abort the process. Then, run `colabfold_batch` on the compute node with GPU and you can perform the structure prediction without internet.
> 
> Indeed, since such cases are common, it would be convenient for users to provide an option to retrieve only MSA and templates, but this has not been implemented yet.

Dear developer,
Recently I want to run localcolabfold on a sever without access to Internet, and I have tried to do so as you mentioned here to creat a .a3m file and .cif files of templates on my own PC and disconnect my PC's internet connection to simluate the situation  on the sever.
However, I encounter some problems when I try to use `--template` parameters on the sever. If I only run `colabfold_batch --templates --amber --model-type alphafold2_multimer_v3 ./test.a3m ./output_test` without `--custom-template-path`, colabfold will try to download templates file via Internet ,which will fail; Also, If I try to use the `--custom-template-path` to specify the path of .cif files (I move all templates for different chains to a single file), the colabfold will report an error :

- 2023-10-11 16:08:56,198 Found 8 citations for tools or databases
2023-10-11 16:09:40,124 Query 1/1: test (length 80)
2023-10-11 16:10:11,077 Sequence 0 found templates: ['5o9z_v', '5zya_C', '7onb_C', '5ife_C', '7abg_u', '7b92_C', '6qx9_B1', '7q4o_A', '7abh_u', '7abi_u', '7dvq_1', '6ah0_1', '6ahd_1', '5z56_1', '6g90_O', '5gm6_G', '7dco_1', '5lqw_Q']
2023-10-11 16:10:11,077 Could not get MSA/templates for test: list index out of range
Traceback (most recent call last):
  File "/mnt/f/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1385, in run
    = get_msa_and_templates(jobname, query_seqs_unique, a3m_lines, result_dir, 'single_sequence', use_templates,
  File "/mnt/f/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 785, in get_msa_and_templates
    a3m_lines_mmseqs2[index],
IndexError: list index out of range
2023-10-11 16:10:11,082 Done

Here is the frist output dictionary of my own PC, where colabfold was aborted after MSA and templates downloading

![image](https://github.com/YoshitakaMo/localcolabfold/assets/97963098/d6d2912b-98cf-4ead-8983-ab360b276aa2)

Thanks for your reading!

**Comment by YoshitakaMo** [comment]
Sorry for the inconvenience. The cause of issue is probably https://github.com/YoshitakaMo/localcolabfold/issues/182 .
Now the issue has been fixed. Please update the localcolabfold and test it again!
