### ISSUE TITLE
[Potential Bug] Customized MSA file for Multimer prediction.

### ISSUE THREAD

**Issue by suyufeng** [YoshitakaMo/localcolabfold#182]
My setting is [use template + multimer + use a3m file as input].

The error is 
 File "/lib/python3.10/site-packages/colabfold/batch.py", line 783, in get_msa_and_templates
    a3m_lines_mmseqs2[index],
IndexError: list index out of range

If I understand the code correctly, we should change  "/lib/python3.10/site-packages/colabfold/batch.py", line 1383

 = get_msa_and_templates(jobname, query_seqs_unique, **a3m_lines**, result_dir, 'single_sequence', use_templates,

to

 = get_msa_and_templates(jobname, query_seqs_unique, **unpaired_msa**, result_dir, 'single_sequence', use_templates,

This is because a3m_lines is just a list of lines in the original input a3m file (according to function get_queries in colabfold/batch.py),  so len(a3m_lines) should be 1 which doesn't match len(query_sequences) in the multimer prediction setting. So we may need to use unpaired_msa instead.

I am not sure whether I understand the code correctly. Looking forward to receiving your response!

**Comment by YoshitakaMo** [comment]
Thank you for reporting this potential but serious bug! I've fixed it in the ColabFold repository.

**Comment by suyufeng** [comment]
Thanks for the reply!
