### ISSUE TITLE
Question:TensoRT requirement

### ISSUE THREAD

**Issue by ryupath** [YoshitakaMo/localcolabfold#190]
**What is your installation issue?**

Although gpu is working(nvidia-smi), there is an error message that TensorRT is not installed.
Is this a necessary library ?

**Computational environment**

 - OS: [e.g. Ubuntu 22.04]
 - CUDA version 11.8

**To Reproduce**
Multimer prediction

**Comment by bb-cryoEM** [comment]
I also get this error on a linux installation.

It appears TensorFlow 2.0.12 is installed in the ColabFold environment during installation. I assume this means TensorRT is not supported/required, but commenting to confirm.

**Comment by zmactep** [comment]
I have the same error in my WSL2 environment. Cannot run even the simple single-domain folding.

**Comment by YoshitakaMo** [comment]
The warning message is now suppressed thanks to [silence-tensorflow](https://pypi.org/project/silence-tensorflow/).
