### ISSUE TITLE
Question: If I have multiple GPUs, can I specify to run colabfold on separate GPU?

### ISSUE THREAD

**Issue by JasonIsaac-Lofty** [YoshitakaMo/localcolabfold#200]
I have multiple GPU on our server, can I run colabfold on separate GPU like alphafold2, just by using the flag: --gpu_devices?

**Comment by ChrisLou-bioinfo** [comment]
yes？

**Comment by sean-workman** [comment]
This is a really unhelpful answer. There is no --gpu_devices flag in the Flags section of the read me or in the usage message from --help.

**Comment by YoshitakaMo** [comment]
How about setting `CUDA_VISIBLE_DEVICES` environment variable manually? For example,

```bash
```

**Comment by sean-workman** [comment]
Hi @YoshitakaMo, I did indeed end up setting specific devices as visible in the bash scripts I wrote. Thank for maintaining this great resource!

**Comment by JasonIsaac-Lofty** [comment]
> How about setting `CUDA_VISIBLE_DEVICES` environment variable manually? For example,
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 colabfold_batch --amber --templates <input> <outputdir>
> CUDA_VISIBLE_DEVICES=1 colabfold_batch --amber --templates <input> <outputdir>
> ...
> ```

Thank you very much!  That was really helpful!
