### ISSUE TITLE
Installation issue. Alphafold is not installed.

### ISSUE THREAD

**Issue by rcrehuet** [YoshitakaMo/localcolabfold#206]
**Caution: Please only report your issue related to the installation on your local PC or macOS.** If you can get the help message by `colabfold_batch --help` or run a test prediction successfully, your installation is successful. Requests or questions regarding ColabFold features should be directed to [ColabFold repo's issues](https://github.com/sokrypton/ColabFold/issues).

----

**What is your installation issue?**

Installation ends with 
```
-----------------------------------------
Installation of ColabFold finished.
Add /home/ramon/progs/localcolabfold/colabfold-conda/bin to your PATH environment variable to run 'colabfold_batch'.
```
But when calling colafold_batch I get the following error:
```
[ramon@blauet ~]$ colabfold_batch
Traceback (most recent call last):
  File "/home/ramon/progs/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 33, in <module>
    import alphafold
ModuleNotFoundError: No module named 'alphafold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ramon/progs/localcolabfold/colabfold-conda/bin/colabfold_batch", line 5, in <module>
    from colabfold.batch import main
  File "/home/ramon/progs/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 35, in <module>
    raise RuntimeError(
RuntimeError: 

alphafold is not installed. Please run `pip install colabfold[alphafold]`
```
Should I install alphafold this way?

**Computational environment**

 - OS: Rocky Linux 9.3
 - CUDA version if Linux (Show the output of `/usr/local/cuda/bin/nvcc --version`.)
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```

Same behaviour is obtain in another machine with:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**To Reproduce**

Call `colabfold_batch` from shell.

**Expected behavior**

colabfold_batch should run.

**Comment by hyeh20** [comment]
Running "pip install colabfold[alphafold]" fixes the issue for me

**Comment by KCore1** [comment]
The above didn't work for me, but running the update_linux.sh file did

**Comment by rcrehuet** [comment]
Thank you. Running `pip install colabfold[alphafold]` worked for me. In both computers.
