### ISSUE TITLE
Question:install issue 'no module named alphafold'

### ISSUE THREAD

**Issue by qianhui1222** [YoshitakaMo/localcolabfold#207]
**Caution: Please only report your issue related to the installation on your local PC or macOS.** If you can get the help message by `colabfold_batch --help` or run a test prediction successfully, your installation is successful. Requests or questions regarding ColabFold features should be directed to [ColabFold repo's issues](https://github.com/sokrypton/ColabFold/issues).

----

**What is your installation issue?**
when type nvcc --version:
 Command 'nvcc' not found, but can be installed with:
apt install nvidia-cuda-toolkit
Please ask your administrator.
so i tried nvidia-smi and get CUDA Version: 11.0 

I try to install colabfold on school computing platform and i checked the log file seems like everything was fine, but when i try   colabfold_batch --help
it shows:
Traceback (most recent call last):
  File "~/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 33, in <module>
    import alphafold
ModuleNotFoundError: No module named 'alphafold'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/localcolabfold/colabfold-conda/bin/colabfold_batch", line 5, in <module>
    from colabfold.batch import main
  File "~/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 35, in <module>
    raise RuntimeError(
RuntimeError: 

alphafold is not installed. Please run `pip install colabfold[alphafold]`

**Computational environment**
NVIDIA DGX Server Version 5.3.1 (GNU/Linux 5.4.0-120-generic x86_64) 
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**To Reproduce**

**Expected behavior**

**Comment by YoshitakaMo** [comment]
Sorry for the inconvenience. The issue is now fixed. Please try the installation again.

**Comment by qianhui1222** [comment]
Thanks, now the installation has been successful!
