### ISSUE TITLE
Numerous NumPy issues after update

### ISSUE THREAD

**Issue by masifali404** [YoshitakaMo/localcolabfold#216]
**Caution: Please only report your issue related to the installation on your local PC or macOS.** If you can get the help message by `colabfold_batch --help` or run a test prediction successfully, your installation is successful. Requests or questions regarding ColabFold features should be directed to [ColabFold repo's issues](https://github.com/sokrypton/ColabFold/issues).

----

**What is your installation issue?**

I had the np.int error like another user did, fixed that but now I am getting this error. This happened after updating and I assume it will continue getting multiple dependency errors. Is there a way to undo the update or is there a script to take care of all of the dependency related issues?

**Computational environment**

 - OS: Ubuntu 22.04
 - CUDA version if Linux:
 - nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

**To Reproduce**

1. ran command: colabfold_batch --help
2. ERROR BELOW:
anaconda3/lib/python3.9/site-packages/alphafold/data/templates.py:92: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  'template_domain_names': np.object,
Traceback (most recent call last):
  File "/home/asif-gca/anaconda3/bin/colabfold_batch", line 5, in <module>
    from colabfold.batch import main
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/colabfold/batch.py", line 43, in <module>
    from alphafold.data import (
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/alphafold/data/feature_processing.py", line 20, in <module>
    from alphafold.data import msa_pairing
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/alphafold/data/msa_pairing.py", line 23, in <module>
    from alphafold.data import pipeline
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/alphafold/data/pipeline.py", line 23, in <module>
    from alphafold.data import templates
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/alphafold/data/templates.py", line 92, in <module>
    'template_domain_names': np.object,
  File "/home/asif-gca/anaconda3/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Expected behavior**

For it to work.

**Comment by YoshitakaMo** [comment]
Probably you're using an old version of LocalColabFold because I see python3.9 in your log. Currently, python3.10 is used. Please your localcolabfold freshly and test it.

**Comment by masifali404** [comment]
Thank you, that fixed the issue.
