### ISSUE TITLE
Question: Is it possible to output a table of IDDT / pLDDTs?

### ISSUE THREAD

**Issue by dbolser** [YoshitakaMo/localcolabfold#217]
The tool nicely outputs a PNG with predicted IDDT against position in the chain, but I'd really like to get that data as a table.

Searching the output directories, I can't seem to find it... Is it in there somewhere?

Is there a flag to generate it?

Many thanks,
Dan.

**Comment by YoshitakaMo** [comment]
plddt, pae, max_ptm, ptm, and iptm values are stored in files named `**_scores_rank_00*_alphafold2_**_*_model_*_seed_00*.json`. You can parse these values per the predicted `pdb` file.
