### ISSUE TITLE
GPU Memory failed to allocate

### ISSUE THREAD

**Issue by cochan424** [YoshitakaMo/localcolabfold#22]
I am trying to run colabfold on >2500 aa sequence. I read the other thread #7 regarding adjusting the following settings:

```
#!/bin/bash 
export TF_FORCE_UNIFIED_MEMORY=1 
export XLA_PYTHON_CLIENT_MEM_FRACTION=4.0 
colabfold-conda/bin/python3.7 runner.py
```

If I follow [https://sbgrid.org/wiki/examples/alphafold2](https://sbgrid.org/wiki/examples/alphafold2) recommendations:
```
TF_FORCE_UNIFIED_MEMORY=1
XLA_PYTHON_CLIENT_MEM_FRACTION=0.5
XLA_PYTHON_CLIENT_ALLOCATOR=platform
```

Either way, I have been running into the following error:

`tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7`

`jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Resource exhausted: Failed to allocate request for 3.25GiB (3488555008B) on device ordinal 0`

Checking `nvidia-smi` indicated that the primary half of the memory of one GPU is being used and not the rest. I tried restarting my ssh sessions too to make sure nothing else was being unknowingly used in the background prior to running this command.

**Comment by truatpasteurdotfr** [comment]
`export CUDA_VISIBLE_DEVICES=0` or any value to use only one gpu, no solution for the out of memory pb than getting a bigger gpu...

**Comment by cochan424** [comment]
Yeah so I rerun the command every couple of seconds. Doesn't go over 50%. Yeah, still crashes with the same error.
