### ISSUE TITLE
How to bypass the server when using MSA single sequence and have .cif file as template. 

### ISSUE THREAD

**Issue by johnny-rodriguez** [YoshitakaMo/localcolabfold#226]
I am running the following colabfold command:
colabfold_batch
--num-recycle 3
--msa-mode single_sequence
--amber
--use-gpu-relax
--num-relax 1
--num-model 2
--model-order 1,2
--templates
--custom-template-path $newdir
--overwrite-existing-results
$filename.fasta $af2_output

I do not expect to use any MSAs other than the single sequence and the only template required is the .cif file template I am providing. However, it is still connecting to the server. Since I am running a hundreds of structures, I am running into rate limits. How can I bypass the server?

**Comment by johnny-rodriguez** [comment]
Thanks for the response. I tried using a3m file that has the following format:
#73,91  1
>101
MAEVEAALATAKYLLEKAKESKDKKEAEGFAAQATKAAKGAEALAKELGINPEEAAKAAEKITAEGKAAAEKK-------------------------------------------------------------------------------------------
>102
-------------------------------------------------------------------------TFFHYTKLMNTHWLRHGMGKGKWREELWMFKTHTHFFKLKFWTWQHERPLFIEWFMFKWHTFWFKFKFKHRMRMEWRWRHRHEHEHRHRRW

This is the command I used:
colabfold_batch \
      --num-recycle 3 \
      --amber \
      --use-gpu-relax \
      --num-relax 1 \
      --num-model 2 \
      --model-order 1,2 \
      --templates \
      --custom-template-path $newdir \
      --overwrite-existing-results \
      $filename.a3m $af2_output

This is the error I received:
2024-04-06 16:10:22,264 Running colabfold 1.5.5 (a00ce1bcc477491d7693e3816d21ea3fc2cf40fd)
2024-04-06 16:10:22,503 Running on GPU
2024-04-06 16:10:22,933 Found 9 citations for tools or databases
2024-04-06 16:10:23,063 Query 1/1: aaaj (length 164)
2024-04-06 16:10:23,359 Sequence 0 found templates: ['aaaj_A']
2024-04-06 16:10:23,589 Sequence 1 found templates: ['aaaj_B']
2024-04-06 16:10:23,589 Could not generate input features aaaj: MSA 0 must contain at least one sequence.
Traceback (most recent call last):
  File "/data/AI_tools/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1488, in run
    = generate_input_feature(query_seqs_unique, query_seqs_cardinality, unpaired_msa, paired_msa,
  File "/data/AI_tools/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 1024, in generate_input_feature
    feature_dict.update(build_multimer_feature(input_msa))
  File "/data/AI_tools/localcolabfold/colabfold-conda/lib/python3.10/site-packages/colabfold/batch.py", line 879, in build_multimer_feature
    for k, v in pipeline.make_msa_features([parsed_paired_msa]).items()
  File "/data/AI_tools/localcolabfold/colabfold-conda/lib/python3.10/site-packages/alphafold/data/pipeline.py", line 64, in make_msa_features
    raise ValueError(f'MSA {msa_index} must contain at least one sequence.')
ValueError: MSA 0 must contain at least one sequence.
2024-04-06 16:10:23,590 Done

I have also tried a standard .fasta file, but it gave me a special character error because of the colon separating the two proteins of interest
I have also tried removing the colon, but instead it fused the two proteins of interest together..

**Comment by gezmi** [comment]
To my experience, the a3m file format is a little bit different then from here, e.g. the 102 appears twice. Also the < sign is missing, but that might be a github problem. Once I also reproduced the a3m file, and there were some very subtle things that needs to match exactly to get it to work.

**Comment by YoshitakaMo** [comment]
This will surely work.
```
#73,91	1,1
>101	102
MAEVEAALATAKYLLEKAKESKDKKEAEGFAAQATKAAKGAEALAKELGINPEEAAKAAEKITAEGKAAAEKKTFFHYTKLMNTHWLRHGMGKGKWREELWMFKTHTHFFKLKFWTWQHERPLFIEWFMFKWHTFWFKFKFKHRMRMEWRWRHRHEHEHRHRRW
>101
MAEVEAALATAKYLLEKAKESKDKKEAEGFAAQATKAAKGAEALAKELGINPEEAAKAAEKITAEGKAAAEKK-------------------------------------------------------------------------------------------
>102
-------------------------------------------------------------------------TFFHYTKLMNTHWLRHGMGKGKWREELWMFKTHTHFFKLKFWTWQHERPLFIEWFMFKWHTFWFKFKFKHRMRMEWRWRHRHEHEHRHRRW
```
The first line starting with `#` requires info of each sequence length (e.g. 73 and 91) and the stoichiometry (1,1). Insert a TAB between these two.

**Comment by johnny-rodriguez** [comment]
Awesome. That works. Thank you!

**Comment by johnny-rodriguez** [comment]
Awesome. That works! Thank you!
