### ISSUE TITLE
Cyclic peptide Question:

### ISSUE THREAD

**Issue by aishiba0721** [YoshitakaMo/localcolabfold#232]
Hello, I am using this project to predict the docking pose of cyclic peptides with proteins. I am using several examples from the original paper, such as 1SFI and 3AV9. The input format is in the form of a CSV file, and the sequence is formatted as described in the tutorial, with a colon separating the protein and cyclic peptide parts，such as “1SFI,IVGGYTCGANTVPYQVSLNXXSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLXGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTXSCASXAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKXXXXLQGIVSWGSXGCAQKNKPGVYTKVCNYVSWIKQTIASN:GRCTKSIPPICFPD”. However, I have noticed that the predicted peptides in the results are not forming cyclic peptides, but rather linear peptides. Thank you for any replies.

**Comment by YoshitakaMo** [comment]
AlphaFold2/ColabFold doesn't support a prediction of cyclic peptides currently...

**Comment by nachotu** [comment]
Hi @YoshitakaMo, Now  [AlphaFold2_advanced_v2](https://colab.research.google.com/github/sokrypton/ColabDesign/blob/gamma/af/examples/predict.ipynb) can predict cyclic peptides complexes. These changes are implemented now in localcolabfold?
Thank you
