### ISSUE TITLE
Question:"Error downloading files" when trying to use deepfold model

### ISSUE THREAD

**Issue by CykaZH** [YoshitakaMo/localcolabfold#237]
When attempting to download the deepfold_v1 model, an error occurred (RuntimeError: Error downloading files). Could this be due to my network issue?
![20240514174149](https://github.com/YoshitakaMo/localcolabfold/assets/128057850/85337cbd-31d3-42ac-a7c2-2a3f43d9e64e)

**Comment by CykaZH** [comment]
Solved by downloading the relevant packages from the websites noted in download.py directly.

**Comment by gieses** [comment]
I just saw the model by chance today. Google was not very helpful except for bringing me here, so I assume deepfold is WIP project?
