### ISSUE TITLE
Documentation unclear on where to run the update script

### ISSUE THREAD

**Issue by nejmeijer** [YoshitakaMo/localcolabfold#266]
In the section on how to update an existing installation, both the English and Japanese READMEs mention a "`colabfold_batch` directory", but no directory by that name exists. Interpreting this as "the directory of `colabfold_batch`" yields e.g. `~/localcolabfold/colabfold-conda/bin/` (if it was installed in the user's home directory), which is also incorrect.

From the code in the update script the intended directory seems to be `~/localcolabfold/` (again assuming an installation in the home directory). Perhaps the documentation should be changed to reflect this.

**Comment by YoshitakaMo** [comment]
Thanks, @nejmeijer ! That's correct. I've merged your PR!
