### ISSUE TITLE
Missing tmp.id90.fas file while running in paired mode

### ISSUE THREAD

**Issue by gundalav** [YoshitakaMo/localcolabfold#29]
Hi Yoshitaka-san,

I was trying  [my_af2_input.fasta.txt](https://github.com/YoshitakaMo/localcolabfold/files/7438941/my_af2_input.fasta.txt) file. Notice that there, I use `:` for modeling  protein-protein hetero-complexes. 

I used this command line:

```
/home/ubuntu/storage1/colabfold/bin/colabfold --input my_af2_input.fasta.txt \
    --output my_output_dir \
    --use_ptm \
    -p paired \
    -r 10 \
    --num_relax Top5

```

Basically I wanted to optimize the result with pairing option.

I get the following error

```
COLABFOLD_PATH is set to /home/ubuntu/storage1/colabfold
Input ID: lrp1/hmgb1.144
Input Sequence: CSNLCLLSPGGGHKCACPTNFYLGSDGRTCVSNCTASQFVCKNDKCIPFWWKCDTEDDCGDHSDEPPDCPEFKCRPGQFQCSTGICTNPAFICDGDNDCQDNSDEANCDIHVCLPSQFKCTNTNRCIPGIFRCNGQDNCGDGEDERDCPEVTCAPNQFQCSITKRCIPRVWVCDRDNDCVDGSDEPANCTQMTCGVDEFRCKDSGRCIPARWKCDGEDDCGDGSDEPKEECDERTCEPYQFRCKNNRCVPGRWQCDYDNDCGDNSDEESCTPRPCSESEFSCANGRCIAGRWKCDGDHDCADGSDEKDCTPRCDMDQFQCKSGHCIPLRWRCDADADCMDGSDEEACGTGVRTCPLDEFQCNNTLCKPLAWKCDGEDDCGDNSDENPEECARFVCPPNRPFRCKNDRVCLWIGRQCDGTDNCGDGTDEEDCEPPTAHTTHCKDKKEFLCRNQRCLSSSLRCNMFDDCGDGSDEEDCSIDPKLTSCATNASICGDEARCVR:MGKGDPKKPRGKMSSYAFFVQTCREEHKKKHPDASVNFSEFSKK
homooligomer: 1:1
total_length: 544
output_dir: /home/ubuntu/storage1/make_or_dock_peptide_with_alphafold2/af2_output/my_output_dir
attempting to pair some sequences...
running mmseqs2_noenv_nofilter on all seqs
prepping seq_0
prepping seq_1
attempting pairwise stitch for 0 1
  0%|          | 0/13025 [elapsed: 00:00 remaining: ?]
sh: 1: colabfold-conda/bin/hhfilter: not found
Traceback (most recent call last):
  File "/home/ubuntu/storage1/colabfold/runner_af2advanced.py", line 163, in <module>
    hhfilter_loc="colabfold-conda/bin/hhfilter", precomputed=precomputed, TMP_DIR=output_dir)
  File "/home/ubuntu/storage1/colabfold/colabfold_alphafold.py", line 368, in prep_msa
    for line in open(f"{TMP_DIR}/tmp.id90.fas","r"):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/storage1/make_or_dock_peptide_with_alphafold2/af2_output/hmgb1.144_dock_lrp1_yamada.paired.r10/tmp.id90.fas'
```
It has no problem when I use `-p` option.
How can I resolve it?

G.V.

**Comment by CYP152N1** [comment]
The problem caused by the filename extension of input file.
.fasta file is only supported.
you should remove .txt of input file name.

>/home/ubuntu/storage1/make_or_dock_peptide_with_alphafold2/af2_output/hmgb1.144_dock_lrp1_yamada.paired.r10/tmp.id90.fas'

The temporary file name "mp.id90.fas" means  "6 letter subtraction of  XXXX.fas|ta.txt" to remove  fasta extension XXXXX|.fasta from input file

**Comment by gundalav** [comment]
@CYP152N1 I tried with `my_af2_input.fasta` (after removing `txt`). It still failed. Please test my code too.

**Comment by CYP152N1** [comment]
2021-11-03 01:42:59.721869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1, 2
sequence=CSNLCLLSPGGGHKCACPTNFYLGSDGRTCVSNCTASQFVCKNDKCIPFWWKCDTEDDCGDHSDEPPDCPEFKCRPGQFQCSTGICTNPAFICDGDNDCQDNSDEANCDIHVCLPSQFKCTNTNRCIPGIFRCNGQDNCGDGEDERDCPEVTCAPNQFQCSITKRCIPRVWVCDRDNDCVDGSDEPANCTQMTCGVDEFRCKDSGRCIPARWKCDGEDDCGDGSDEPKEECDERTCEPYQFRCKNNRCVPGRWQCDYDNDCGDNSDEESCTPRPCSESEFSCANGRCIAGRWKCDGDHDCADGSDEKDCTPRCDMDQFQCKSGHCIPLRWRCDADADCMDGSDEEACGTGVRTCPLDEFQCNNTLCKPLAWKCDGEDDCGDNSDENPEECARFVCPPNRPFRCKNDRVCLWIGRQCDGTDNCGDGTDEEDCEPPTAHTTHCKDKKEFLCRNQRCLSSSLRCNMFDDCGDGSDEEDCSIDPKLTSCATNASICGDEARCVR:MGKGDPKKPRGKMSSYAFFVQTCREEHKKKHPDASVNFSEFSKK
out:test2
ColabFold on Linux
homooligomer: '1:1'
total_length: '544'
working_directory: 'prediction/test2_20211103_0143'
running mmseqs2
attempting to pair some sequences...
running mmseqs2_noenv_nofilter on all seqs
  0%|          | 0/300 [elapsed: 00:00 remaining: ?]
prepping seq_0
prepping seq_1
attempting pairwise stitch for 0 1
  0%|          | 0/13220 [elapsed: 00:00 remaining: ?]
found 141 pairs
24507 Sequences Found in Total
  0%|          | 0/5 [elapsed: 00:00 remaining: ?]
2021-11-03 01:43:21.810140: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-03 01:43:21.812838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-03 01:43:21.812856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2021-11-03 01:43:21.883220: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3700180000 Hz

humm... pair_msa was proceeded in the previous version of localcolabfold . 
Sorry, I can't upgrade the latest localcolabfold now owing to self update of runner.py.
I have nothing to check and solve this problem.
