### ISSUE TITLE
localcolabfold doesn't work on WSL (Windows)

### ISSUE THREAD

**Issue by Phreely** [YoshitakaMo/localcolabfold#31]
I installed localcolabfold on Ubuntu running in Windows WSL.
Installation using $ bash install_colabfold_linux.sh worked well.
If I cd into colabfold and run
$ colabfold-conda/bin/python3.7 runner.py
I get the following message:
-bash: colabfold-conda/bin/python3.7: No such file or directory
If I check the folders within the colabfold folder using ls I get this:
CONTRIBUTING.md  colabfold.py               docker               notebooks         residue_constants.patch  scripts
LICENSE          colabfold_alphafold.patch  gpurelaxation.patch  pairmsa.py        run_alphafold.py         setup.py
README.md        colabfold_alphafold.py     imgs                 protein.patch     run_alphafold_test.py
alphafold        conda                      model.patch          reformat.pl       runner.py
bin              config.patch               modules.patch        requirements.txt  runner_af2advanced.py

So there is no colabfold-conda folder. Is this a typo and it should read colabfold/conda/bin... ?
I can run the script using
$ python3 runner.py
but then there's a tensorflow issue.

**Comment by YoshitakaMo** [comment]
For some reason, it seems the installation of `colabfold-conda` failed. Try these commands below line by line.

```
# Enter your colabfold directory (e.g. `/home/moriwaki/colabfold`)
COLABFOLDDIR="set your colabfold directory"

echo "Creating conda environments with python3.7 as ${COLABFOLDDIR}/colabfold-conda"
. "${COLABFOLDDIR}/conda/etc/profile.d/conda.sh"
export PATH="${COLABFOLDDIR}/conda/condabin:${PATH}"
conda create -p $COLABFOLDDIR/colabfold-conda python=3.7 -y
conda activate $COLABFOLDDIR/colabfold-conda
conda update -n base conda -y
```

then `colabfold-conda` directory will be created. If some errors occured, please report here.

If it is successfully installed, execute the rest commands after line 68 of https://github.com/YoshitakaMo/localcolabfold/blob/main/install_colabfold_linux.sh.
