### ISSUE TITLE
runner.py vs runneraf2advanced.py and run time

### ISSUE THREAD

**Issue by seanco-hash** [YoshitakaMo/localcolabfold#32]
Hi,
Thanks for this repo it is amazing.

Can you explain the difference between runner.py and runneraf2advanced.py?
Are both run with the latest update that boosted the running time?

I run runner.py multiple times (only single compile in the beggining of course)
on gpu:
Nvidia  DGX - A100 P3687 System 8 x 80GB
With varied length sequences.

Currently it run in pace of 15-20 structures in hour (each structure produced by single model with max recycke 3)
It is fast but not as thousands of models in a day.
How can I be sure that I use it correctly?

thanks

**Comment by YoshitakaMo** [comment]
> Can you explain the difference between runner.py and runneraf2advanced.py?

Almost the same. runner.py is the prototype and hardcoded one. runner_af2advanced.py is a modified version of runner.py that can take arguments from CUI. I recommend using the latter one or `colabfold` command.

> Are both run with the latest update that boosted the running time?
> Currently it run in pace of 15-20 structures in hour (each structure produced by single model with max recycle 3)
> It is fast but not as thousands of models in a day.
> How can I be sure that I use it correctly?

The pace is reasonable. It takes at least 5–10 minutes to output 5 structures per sequence, and more time is needed to obtain the MSA.
