### ISSUE TITLE
TypeErrorr: __init__() got an unexpected keyword argument 'is_training'

### ISSUE THREAD

**Issue by gagawenw** [YoshitakaMo/localcolabfold#33]
hello, I meet the problem when I use mmseqs2. I don't know how to solve it
![2091636107522_ pic](https://user-images.githubusercontent.com/61271468/140495934-ecbb9d46-dee2-4df9-b20f-cca2c50f27a8.jpg)
Thank you

**Comment by universvm** [comment]
did you end up fixing this?
