### ISSUE TITLE
AF2_advanced crashed upon processing sequence with repeat

### ISSUE THREAD

**Issue by gundalav** [YoshitakaMo/localcolabfold#35]
Hi Yoshitaka-san,

I tried running AF2_Advanced on these two files separately:

```
>HHAWx4
HHAWHHAWHHAWHHAW
```

And 

```
>KKAWx4
KKAWKKAWKKAWKKAW
```

It gave me the following error message:

```
running mmseqs2
  0%|          | 0/150 [elapsed: 00:00 remaining: ?]
Traceback (most recent call last):
  File "/home/ubuntu/storage1/colabfold/runner_af2advanced.py", line 163, in <module>
    hhfilter_loc="colabfold-conda/bin/hhfilter", precomputed=precomputed, TMP_DIR=output_dir)
  File "/home/ubuntu/storage1/colabfold/colabfold_alphafold.py", line 292, in prep_msa
    A3M_LINES = cf.run_mmseqs2(I["seqs"], prefix, use_filter=True, host_url=mmseqs_host_url)
  File "/home/ubuntu/storage1/colabfold/colabfold.py", line 150, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.

```

How can I resolve the issue?

G.V.

**Comment by YoshitakaMo** [comment]
> Please confirm your input is a valid protein sequence. 

This is not an issue of localcolabfold, but mmseqs2. The two sequences you showed gave the same error in my localcolabfold environment. Did you test them on GoogleColab-AlphaFold2_advanced.ipynb? I guess it will cause an error.
Please test it on the notebook before you report here.

**Comment by gundalav** [comment]
> > Please confirm your input is a valid protein sequence.
> 
> This is not an issue of localcolabfold, but mmseqs2. The two sequences you showed gave the same error in my localcolabfold environment. Did you test them on GoogleColab-AlphaFold2_advanced.ipynb? I guess it will cause an error. Please test it on the notebook before you report here.

Yoshitaka-san, 

You're right. I tried on `GoogleColab-AlphaFold2_advanced.ipynb`.
It gives the same error message. I'll check with them. 

G.V.
