### ISSUE TITLE
Using Jackhmmer or custom msa file?

### ISSUE THREAD

**Issue by gitgyj** [YoshitakaMo/localcolabfold#36]
First of all, thanks for your effort to share this nice work, it's very helpful. 

I had some queries that have very low MSA coverage using mmseqs2 compared to using jackhmmer, so I am wondering if there is a new runner.py now would support jackhmmer, I noticed that the original runner.py doesn't work. 
Or if is there anyway to upload a custom msa file? When I ran the py file, with custom-msa, it doesn't give me option to upload file. Thanks!

**Comment by CYP152N1** [comment]
README
FAQ
・Is it possible to create MSA by jackhmmer?
No, it is not currently supported.

**Comment by YoshitakaMo** [comment]
Hi @gitgyl,

I'm sorry for this late reply. Now I am ready to provide a new version 1.2.0 of localcolabfold, which can use your own msa file. Please install and use it!
