### ISSUE TITLE
Is there a way to suppress pop-up graphics ?

### ISSUE THREAD

**Issue by msleutel** [YoshitakaMo/localcolabfold#38]
First off, fantastic piece of code, thank you so much for your efforts.

We are trying to using localcolabfold to do batch predictions, but we encounter the following problem. Whenever a graphical output is being generated on the fly (i.e. a new window is opened depicting the graphic), colabfold stalls on our system until that window is closed, only to proceed to the next point where another graphics window is opened. Having set "show_images = False" which I believe suppresses the depiction of the predicted structures, still leads to stalling events for the other images that are being generated. 

Can you suggest a workaround ?

Thanks in advance

**Comment by YoshitakaMo** [comment]
Hi, Msleutel, How about commenting out `plt.show()` in `runner_af2advanced.py`?

```patch
  cf.plot_msas(mod_I["msas"], mod_I["ori_sequence"], return_plt=False)
  plt.savefig(os.path.join(I["output_dir"],"msa_coverage.filtered.png"), bbox_inches = 'tight', dpi=200)
  # plt.show()

---

if use_ptm:
  print("predicted alignment error")
  cf.plot_paes([outs[k]["pae"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
  plt.savefig(os.path.join(I["output_dir"],f'predicted_alignment_error.png'), bbox_inches = 'tight', dpi=np.maximum(200,dpi))
#  plt.show()

print("predicted contacts")
cf.plot_adjs([outs[k]["adj"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(os.path.join(I["output_dir"],f'predicted_contacts.png'), bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()

print("predicted distogram")
cf.plot_dists([outs[k]["dists"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(os.path.join(I["output_dir"],f'predicted_distogram.png'), bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()

print("predicted LDDT")
cf.plot_plddts([outs[k]["plddt"] for k in model_rank], Ls=Ls_plot, dpi=dpi)
plt.savefig(os.path.join(I["output_dir"],f'predicted_LDDT.png'), bbox_inches = 'tight', dpi=np.maximum(200,dpi))
# plt.show()
```

**Comment by msleutel** [comment]
Thank you for the suggestion,

I had tried that in the interim, which does suppress some, but not all pop-up windows. Some of these are being called in colabfold.py. I ended up commenting out those sections entirely (see example below), which is a crude workaround. If someone  finds an actual solution, I'd be happy to learn that.

On a different note, how can I reference localcolabfold: through the github entry ?



#  if return_plt:
#    plt.figure(figsize=(8,5),dpi=dpi)
#    plt.title("Sequence coverage")
#  plt.imshow(lines,
#            interpolation='nearest', aspect='auto',
#            cmap="rainbow_r", vmin=0, vmax=1, origin='lower',
#            extent=(0, lines.shape[1], 0, lines.shape[0]))
#  for i in Ln[1:-1]:
#    plt.plot([i,i],[0,lines.shape[0]],color="black")
#  for i in Ln_dash[1:-1]:
#    plt.plot([i,i],[0,lines.shape[0]],"--",color="black")
#  for j in Nn[1:-1]:
#    plt.plot([0,lines.shape[1]],[j,j],color="black")

#  plt.plot((np.isnan(lines) == False).sum(0), color='black')
#  plt.xlim(0,lines.shape[1])
#  plt.ylim(0,lines.shape[0])
#  plt.colorbar(label="Sequence identity to query")
#  plt.xlabel("Positions")
#  plt.ylabel("Sequences")
#  if return_plt: return plt

**Comment by YoshitakaMo** [comment]
> On a different note, how can I reference localcolabfold: through the github entry ?

You can simply refer "[How do I reference this work?](https://github.com/YoshitakaMo/localcolabfold/blob/main/README.md#how-do-i-reference-this-work)" because localcolabfold is now described in the [preprint of ColabFold](https://www.biorxiv.org/content/10.1101/2021.08.15.456425v2 ).😁
