### ISSUE TITLE
runner.py gives an error because args is not defined

### ISSUE THREAD

**Issue by couunderbarz** [YoshitakaMo/localcolabfold#4]
It seems that command line argments are only available in runner_af2advanced.py according to README.md.
However, when runner_af2advanced.py was added, runner.py was also changed to require the command line argment "num_relax".
Even though num_relax passed to runner.py, it gives an error because args is not defined in runner.py.

**Comment by YoshitakaMo** [comment]
> Even though num_relax passed to runner.py, it gives an error because args is not defined in runner.py.

Thank you for this report. A part of new implementation `runner_af2advanced.py` were mixed up in `runner.py`. I fixed it.
