### ISSUE TITLE
jaxlib version 0.1.74 required

### ISSUE THREAD

**Issue by andzajan** [YoshitakaMo/localcolabfold#40]
Hi, thank you for a great effort. I have a problem after installing on Linux CentOS with message related to the jaxlib version:

``
ValueError: jaxlib is version 0.1.72, but this version of jax requires version 0.1.74.
``

And if I try to run update script it returns error as well:

```
bash-4.2$ pwd

/hpc/shared/colabfold_batch

bash-4.2$ ls

bin  colabfold-conda  conda  stereo_chemical_props.txt  update_linux.sh

bash-4.2$ ./update_linux.sh

Error! colabfold-conda directory is not present in .
```

**Comment by brianlross** [comment]
I also have this problem

**Comment by YoshitakaMo** [comment]
Thanks for your reports. Please tell me your JAX (not jaxlib) version.

```
$ colabfold_batch/colabfold-conda/bin/python3.7 -m pip list | grep "jax"
```

The issue didn't occur yesterday. My colleague also reported the same issue.

**Comment by YoshitakaMo** [comment]
Thanks for your report. My version is:
```
jax                          0.2.25
jaxlib                       0.1.72+cuda111
```
Thus, today's release v0.2.26 of JAX (https://github.com/google/jax/releases ) may cause this issue. I'll check it from now.

**Comment by brianlross** [comment]
Ok thanks! Let me know.

Brian Ross
________________________________

**Comment by andzajan** [comment]
My output is like this:

```
jax                          0.2.26
jaxlib                       0.1.72+cuda111
```

Thank you for looking into it. I guess I could force intall scipt to use jax 0.2.25

**Comment by YoshitakaMo** [comment]
Can you fix your environment with these workarounds?
```
$ colabfold_batch/colabfold-conda/bin/python3.7 -m pip uninstall jax
$ colabfold_batch/colabfold-conda/bin/python3.7 -m pip install jax==0.2.25
```
Then type `colabfold_batch --help` to check whether it works.

**Comment by brianlross** [comment]
Yep that worked.

Thanks!

Brian Ross
________________________________

**Comment by andzajan** [comment]
Can confirm, it is working now. Thanks!

**Comment by YoshitakaMo** [comment]
I update the installer. Thanks for your bug reports!
