### ISSUE TITLE
Where are the pdb files?

### ISSUE THREAD

**Issue by MichaelGajhede** [YoshitakaMo/localcolabfold#42]
Running a very long CPU only job (3 days so far) and model 3 finally finished, model 4 just started. Can I access model 3 pdb at this stage, it is not in the output folder?

**Comment by YoshitakaMo** [comment]
All output pdb structures will be generated after the prediction for all models finishes in the current colabfold version. If you have an update request about it, please visit https://github.com/sokrypton/ColabFold/issues .

**Comment by MichaelGajhede** [comment]
Thanks for answering.
All the best
Michael

Sendt fra min iPad

Den 14. dec. 2021 kl. 03.38 skrev Yoshitaka Moriwaki ***@***.***>:

﻿

You don't often get email from ***@***.*** Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>


All output pdb structures will be generated after the prediction for all models finishes in the current colabfold version. If you have an update request about it, please visit https://github.com/sokrypton/ColabFold/issues<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsokrypton%2FColabFold%2Fissues&data=04%7C01%7Cmig%40sund.ku.dk%7C3e7d3df2b9a74362801508d9beaac45e%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637750462912554523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D9ATCNMCNvbtnwm44%2BT4hUnINfirqjDfKoiR5jxIjDs%3D&reserved=0> .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYoshitakaMo%2Flocalcolabfold%2Fissues%2F42%23issuecomment-993100518&data=04%7C01%7Cmig%40sund.ku.dk%7C3e7d3df2b9a74362801508d9beaac45e%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637750462912554523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fj%2BpJ4BWYwmlqeuAVwXlB71By2EBHn7AIxMkm81wbVc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW47ONM33AG5JIDKNYTP6JDUQ2UZBANCNFSM5J6TPLGA&data=04%7C01%7Cmig%40sund.ku.dk%7C3e7d3df2b9a74362801508d9beaac45e%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637750462912564487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9CltnQ94lk5hTMCwzxTEPrKhG9RC6mpoY39dmLccM2Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmig%40sund.ku.dk%7C3e7d3df2b9a74362801508d9beaac45e%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637750462912564487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zPdBRZpSm533lGMNBQMCPHw3zminQeDXxjbb1VrgjTo%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmig%40sund.ku.dk%7C3e7d3df2b9a74362801508d9beaac45e%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637750462912574437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kq8XNZb0HQIQmPRLeIdJ5e3r1eMSbIwCZjjr85MSolQ%3D&reserved=0>.
