### ISSUE TITLE
Runtime error since the update: "PTX was compiled with an unsupported toolchain"

### ISSUE THREAD

**Issue by seanco-hash** [YoshitakaMo/localcolabfold#44]
Hi,
I used colabfold on my local computer successfully (Thank you guys!)
unfortunately, after I ran the update script, I have an error and I can't run it anymore:

jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.

I tried using cuda 11.1 with cudnn 8.0.5
and tried cuda 11.3 with cudnn 8.2.1
and bothe does not work. 

I installed jax by the instructions an I tried to uninstall and install it again with the specific cuda and cudnn versions - but it didn't help.

I tried to build the colabfold-batch from pip on new enviroment - but it acts the same too.

Any idea what went wrong?

**Comment by YoshitakaMo** [comment]
> the provided PTX was compiled with an unsupported toolchain

This issue is probably not caused by localcolabfold. I think the solution is to upgrade your NVidia Driver to the latest version. My version is 495.29.05.

```
$ nvidia-smi
Mon Dec 27 16:57:42 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:0D:00.0 Off |                  N/A |
|  0%   42C    P8    16W / 350W |      1MiB / 24265MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```
