### ISSUE TITLE
mmseq2 and --host_url

### ISSUE THREAD

**Issue by A-Talavera** [YoshitakaMo/localcolabfold#45]
Hi Yoshitaka,

As colabfold_bash suggests, it recomends using a local version of the mmseq2 to generate the mas.pickle and given the recent problems with the server, do you happen to know how to te set up the search locally, including the required databases? In principle, it should be possible with the argument --host_url.

Thanks a lot in advance.
Best,
Ariel

**Comment by konstin** [comment]
Hi Ariel, how to setup and use the local search is documented in colabfold repository: https://github.com/sokrypton/ColabFold#generating-msas. You don't need to set `--host-url` and there's no pickle involved in this version, you just input a folder of a3m files instead of a folder of fasta files.
