### ISSUE TITLE
slow_operation_alarm error

### ISSUE THREAD

**Issue by jihadsnobre** [YoshitakaMo/localcolabfold#47]
Thank you again, Yoshitaka for this amazing tool! 

Everything works well with installation, however when I try to run colab 

`colabfold_batch --amber --templates --num-recycle 3 --num-models 1 /Users/jihadsnobre1/Desktop/df.csv /Users/jihadsnobre1/Applications/output_files/`

I get this error:

```
Running colabfold 1.2.0 (f5d0cec9e4045666cb615ec9ad89b3bdc1ecda62)
 Found 8 citations for tools or databases
Query 1/1: rpoB (length 1172)
Sequence 0 found templates: [b'6dv9_C' b'6edt_C' b'5zx3_C' b'5uaj_C' b'4yfk_I' b'6pst_I' b'6j9e_C'
 b'2be5_M' b'2o5i_C' b'6woy_C' b'6j9f_C' b'6kf9_B' b'6rfl_B' b'4ayb_B'
 b'5iy9_B' b'6gmh_B' b'5fja_B' b'6rie_B' b'4qiw_B' b'6tut_B']
Running model_3
E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit_apply_fn.109930
********************************
```
I tried to reduce --num-models to 1 and to run and also -- cpu mode, I keep getting the same error.
Any idea of how to fix that? 

Many thanks

**Comment by YoshitakaMo** [comment]
I guess you are running localcolabfold on macOS (`/Users/jihadsnobre1/Applications/...`), not Linux with an NVidia GPU, right? If so, the warning message `Very slow compile?` is always displayed.
Moreover, your input sequence is so long (1172 a.a.) that it takes 5 or more days to produce one model if you use macOS. I strongly recommend using Linux/GPU to reduce the calculation time (1 hour per model). See also the README.

**Comment by jihadsnobre** [comment]
Indeed working on macOS. 
I'm going to let it run to see if after a few days I can still get the result for a single sequence, but yeah I guess getting Linux is the best solution.
Thanks for the quick answer!
