### ISSUE TITLE
Can AlphaFold be used to complete loops?

### ISSUE THREAD

**Issue by fglaser** [YoshitakaMo/localcolabfold#49]
Dear experts,

I wonder if there is a way to use the wonderful power of alphafold just to model missing parts of existing pdbs, e.g. long loops?

I used to use modeller, but it would be great to use alphafold for this taks, specially for long loops.

Thanks!
Fabian

**Comment by YoshitakaMo** [comment]
Hi, @fglaser.
Now that colabfold can take `--custom-template-path` argument to specify a pdb file of interest, now it is possible to complement missing loops.

![colabfold](https://user-images.githubusercontent.com/16487484/158537073-50848052-9091-45cd-9247-a530bf93369c.png)

Here is another example of PDB: 1QG8, which is used as an example in the tutorial of Modeller. https://salilab.org/modeller/wiki/Missing%20residues
![ScreenShot 2022-03-16 16 11 32](https://user-images.githubusercontent.com/16487484/158536862-5e4b8acd-c3d7-4459-8e54-9a0a696c1d5a.png)

To use this feature, please update your localcolabfold first (`./update_linux.sh .`).

Yoshitaka

**Comment by fglaser** [comment]
Dear Yoshita,

I did succeed to get a loops recontruction using alphafold as you suggested, but I noticed alphafold also reconstructed the rest of the molecule, not by much but I would prefer only to build the loops without any reconstruction or update of the rest of the molecule, would it be possible? 

Why the rest of the molecule is updated or modified too?

I used the following command:

colabfold_batch --amber --num-recycle 3 --num-models 2 --model-order 1,2 --templates  --custom-template-path template --msa-mode single_sequence 6vp9_AUX.fasta models_AF_AUX

And the result if you would like to take a looks is the attached model, which has the loops completed, but when if you compare it with the original file (6vp9 chain B) has clear differences.

Thanks!

Fabian




--------------------------
Fabian Glaser, PhD

Structural and Computational Biology Unit
The Lorry I. Lokey Center for Life Sciences and Engineering
Technion - Israel Institute of Technology, Haifa, Israel

**Comment by fglaser** [comment]
Thanks a lot!

This is very useful,

Fabian

--------------------------
Fabian Glaser, PhD

Structural and Computational Biology Unit
The Lorry I. Lokey Center for Life Sciences and Engineering
Technion - Israel Institute of Technology, Haifa, Israel

**Comment by AdrienSchahl** [comment]
Dear Yoshitaka Morikawi, 

I am following this discussion here as I have the same question than @fglaser about rebuilding loops using colabfold : 
Is there any way to build only missing loops and leave the rest of the protein untouched ? 
So far I only found a way to do this by extracting the loops created by AF and pasting them in the template, so I wondered if there was any way to do it automatically.

Best, 

Adrien Schahl

**Comment by camlbrown** [comment]
Also commenting to follow the discussion RE loop addition without full model reconstruction

**Comment by hima111997** [comment]
is there a way to model a missing loop using colabfold leaving the rest of the protein untouched?

**Comment by danielguion** [comment]
Also hoping to follow - hoping to model loops using alphafold while keeping the rest of the protein untouched. Does the colabfold notebook support this? Each time I use my pdb template is fills the loop, but it also predicts the rest of the protein.
