### ISSUE TITLE
How can I use an updated version of the PDB or my own templates?

### ISSUE THREAD

**Issue by Raul-araya-secchi** [YoshitakaMo/localcolabfold#51]
Hi, There is a recently deposited structure on the pdb with high sequence id% with respect to my query protein. However, this structure does not seem to be present on the current PDB database that the colab is using. Is there a way to us an updated version of the PDB or to provide my own set of templates to it?

Thanks.

**Comment by rkruegs123** [comment]
Following. Also interested in using my own templates

**Comment by YoshitakaMo** [comment]
Customized PDB templates are not supported currently...

**Comment by YoshitakaMo** [comment]
Now customized PDB templates are supported. Use `--custom-template-path` arguments.

**Comment by Raul-araya-secchi** [comment]
I know this question is closed, but I just want to add that even using the "single sequence" localcolabfold is not using the templates for the generation of the models. I tried it on the colabfold Advanced 2 and it worked just fine. So, IDK what could be the issue. I updated to the last version of the localcolabfold and got the same issue.
