### ISSUE TITLE
Colab fold Advance

### ISSUE THREAD

**Issue by Raul-araya-secchi** [YoshitakaMo/localcolabfold#54]
Hi,

I have been trying to use the older versions of the localcolabfold that allowed to run  Colab_Fold_Advanced. However I have been unable to make it work. Is there a fork from localcolabfold where is it still working? As I mentioned in another issue I created, I want to use the parameters that allow for the generation of more diverse structures (num_samples, is_training, etc.) but those do not work on the colabfold_batch. 

Thanks.

**Comment by martin-steinegger** [comment]
@Raul-araya-secchi could you please let me know what parameters you'd like to use I can add it to colabfold_batch.

**Comment by martin-steinegger** [comment]
We provide now `training`, in order to use num_samples you could just copy the same sequence N times in a file and active the training mode. Does this work for you?

**Comment by Raul-araya-secchi** [comment]
That’s excellent. Thanks!!

Raul Araya Secchi

On Apr 16, 2022, at 12:31, Martin Steinegger ***@***.***> wrote:

﻿

We provide now training, in order to use num_samples you could just copy the same sequence N times in a file and active the training mode. Does this work for you?
