### ISSUE TITLE
LocalColabFold

### ISSUE THREAD

**Issue by Dilrajl** [YoshitakaMo/localcolabfold#56]
While installing LocalColabFold in the workstation with Ubuntu19.10, I get this message below at the end:

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
install_colabbatch_linux.sh: line 50: cd: /home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold: No such file or directory
sed: can't read batch.py: No such file or directory
install_colabbatch_linux.sh: line 52: cd: /home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/relax: No such file or directory
sed: can't read amber_minimize.py: No such file or directory
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Here is a complete log file from the installation 
[AF2_install.txt](https://github.com/YoshitakaMo/localcolabfold/files/8022854/AF2_install.txt)

When I try to execute "colabfold_batch --help", I get this:
./colabfold_batch: 7: /home/dilraj/Desktop/colabfold_batch/colabfold-conda/bin/colabfold_batch: not found

Is the installation not complete? I will be grateful  if you can provide me pointers as to what I could do to fix this issue.
Please let me know if you need any further information from my end.

Best,
Dilraj

**Comment by YoshitakaMo** [comment]
I couldn't reproduce this situation in my environment.
I think you couldn't install these python packages `colabfold`, `colabfold-1.2.0` and `alphafold_colabfold-2.1.4`in `/home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages`.

To check whether these python packages, type this (change `moriwaki` to `dilraj`):

```
$ ls -lt /home/moriwaki/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages | grep "colabfold"
drwxrwxr-x  5 moriwaki moriwaki    4096  Feb  7 09:39 colabfold
drwxrwxr-x  2 moriwaki moriwaki    4096  Feb  7 09:38 colabfold-1.2.0.dist-info
drwxrwxr-x  2 moriwaki moriwaki    4096  Jan 26 12:02 alphafold_colabfold-2.1.4.dist-info
```

If these packages are not shown, the installation failed.

I haven't found the cause yet, but please try typing the following command to see if it installs ColabFold without errors. 

```
COLABFOLDDIR="/home/dilraj/Desktop/colabfold_batch"
cd ${COLABFOLDDIR}
. "${COLABFOLDDIR}/conda/etc/profile.d/conda.sh"
export PATH="${COLABFOLDDIR}/conda/condabin:${PATH}"
conda activate $COLABFOLDDIR/colabfold-conda
colabfold-conda/bin/python3.7 -m pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"
```

After this command, use the above command to make sure that the `colabfold`, `colabfold-1.2.0` and `alphafold_colabfold-2.1.4` directories are created.

**Comment by Dilrajl** [comment]
Dear Yoshitaka,
                         Yes, the three python packages are indeed not installed. So I tried the commands that you suggested and I am attaching here a log file [log.txt](https://github.com/YoshitakaMo/localcolabfold/files/8033126/log.txt) of the execution. It doesn't mention any error but the python directories (colabfold, colabfold-1.2.0 and alphafold_colabfold-2.1.4) are still not created.

Any further suggestions will be very much appreciated. 

Thank you,
Dilraj

**Comment by YoshitakaMo** [comment]
Ah, according to your installation log, your colabfold may be installed in `~/.local/lib/python3.7/site-packages`. Please check your `~/.local/lib/python3.7/site-packages` directory:

```bash
$ ls -lt ~/.local/lib/python3.7/site-packages | grep "colabfold"
drwxrwxr-x  5 moriwaki moriwaki    4096  Feb  7 09:39 colabfold
drwxrwxr-x  2 moriwaki moriwaki    4096  Feb  7 09:38 colabfold-1.2.0.dist-info
drwxrwxr-x  2 moriwaki moriwaki    4096  Jan 26 12:02 alphafold_colabfold-2.1.4.dist-info
```

If so, please tell me your current environment variable `PYTHONPATH` (check `echo $PYTHONPATH`).

Related to this, the commands below may resolve the installation issue:

```bash
COLABFOLDDIR="/home/dilraj/Desktop/colabfold_batch"
cd ${COLABFOLDDIR}
. "${COLABFOLDDIR}/conda/etc/profile.d/conda.sh"
export PATH="${COLABFOLDDIR}/conda/condabin:${PATH}"
conda activate $COLABFOLDDIR/colabfold-conda
colabfold-conda/bin/python3.7 -m pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold" -t ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages
colabfold-conda/bin/python3.7 -m pip install https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.72+cuda111-cp37-none-manylinux2010_x86_64.whl -t ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages
colabfold-conda/bin/python3.7 -m pip install jax==0.2.25 -t ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages

# hack to share the parameter files in a workstation.
cd ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages/colabfold
sed -i -e "s#props_path = \"stereo_chemical_props.txt\"#props_path = \"${COLABFOLDDIR}/stereo_chemical_props.txt\"#" batch.py
cd ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages/alphafold/relax
sed -i -e 's/CPU/CUDA/g' amber_minimize.py
```

This `-t /path/to/site-packages` specifies the directory to install the packages. If the three packages are successfully installed in `/home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages` after this operation, your colabfold will be ready.

**Comment by Dilrajl** [comment]
Dear Yoshitaka,
                         Yes the three directories (colabfold, colabfold-1.2.0 and alphafold_colabfold-2.1.4) were indeed installed in  ~/.local/lib/python3.7/site-packages.
 
echo $PYTHONPATH gives me **"/home/dilraj/tools/amber18/lib/python3.8/site-packages"**

So, I followed the installation instruction by specifying the "**-t /path/to/site-packages**" and I was able to successfully install the three directories (colabfold, colabfold-1.2.0 and alphafold_colabfold-2.1.4) in "/home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages"

ls -lt /home/dilraj/Desktop/colabfold_batch/colabfold-conda/lib/python3.7/site-packages | grep "colabfold" 

now gives me this

drwxr-xr-x  5 dilraj dilraj    4096 Feb 10 11:19 colabfold
drwxr-xr-x  2 dilraj dilraj    4096 Feb 10 11:10 alphafold_colabfold-2.1.4.dist-info
drwxr-xr-x  2 dilraj dilraj    4096 Feb 10 11:10 colabfold-1.2.0.dist-info

Then I go to "/home/dilraj/Desktop/colabfold_batch/bin" and try "./colabfold_batch --help" , and I get the same message
**./colabfold_batch: 7: /home/dilraj/Desktop/colabfold_batch/colabfold-conda/bin/colabfold_batch: not found**

As a trial, I copied the "colabfold_batch" executable to  "/home/dilraj/Desktop/colabfold_batch/colabfold-conda/bin/colabfold"  and  try "/colabfold_batch --help", I get this:
**/home/dilraj/Desktop/colabfold_batch/colabfold-conda/bin/colabfold_batch: 7: /home/dilraj/Desktop/colabfold_batch/colabfold-conda/bin/colabfold_batch: Argument list too long**

Is something not correct with my environment setting? 

Thank you very much for your patience and support.

**Comment by YoshitakaMo** [comment]
> 2022-02-10 18:14:03.813463: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 10.1.168, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.
> You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.

But I think cuda 11.1 or later is necessary. Is your cuda compiler driver 11.1 or later? Check `nvcc --version`.

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

DO NOT use `nvidia-smi` to check the version.

**Comment by Dilrajl** [comment]
**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168**

Oh I was under the impression that the installation takes care of the cuda driver requirements also.

**Comment by Dilrajl** [comment]
Ok I will do that. Thank you very much again. Very much appreciate.

I will get back to you in case I have any further queries.
