### ISSUE TITLE
Difference with `pip` installation of ColabFold?

### ISSUE THREAD

**Issue by rkruegs123** [YoshitakaMo/localcolabfold#57]
A very basic question -- what is the difference between `LocalColabFold` and the pip installation provided by the `ColabFold` team?

**Comment by YoshitakaMo** [comment]
LocalColabFold has three features that the pip-installed ColabFold does not have.

First, LocalColabFold automatically installs some additional files and packages that are required for `--amber` and `--templates` arguments. Many users would like to use these arguments, but they are not available by default in pip-installed colabfold.
Second, there is a `/path/to/colabfold_batch/bin/colabfold_batch` executable that is a wrapper of the pip-installed colabfold. This also includes some useful environment variables to enable the prediction for a large protein with a.a. length > 1000.
Third, The LocalColabFold installation script provides an independent conda environment, and is also configured for system-wide use on a shared server. I use it with [Environment Modules](https://modules.readthedocs.io/en/latest/).
