### ISSUE TITLE
Getting linux version to work with only CPU when GPU VRAM is insufficient

### ISSUE THREAD

**Issue by zwehrspan** [YoshitakaMo/localcolabfold#6]
Hello,

I have successfully installed localcolabfold on my linux system, and have been able to predict the structures of small proteins. I am now trying to run localcolabfold to predict a large protein; however, the GPU VRAM that I have is insufficient to do it. Specifically, I get the following error message:

2021-09-16 18:37:19.903673: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 12026119256 bytes.

My CPU has more RAM, so I was wondering if there is a way to get localcolabfold to run on only the CPU on Linux? I realize that this will be slower, but that is not a problem for me. 

Thanks in advance!

**Comment by YoshitakaMo** [comment]
You may use `install_colabfold_intelmac.sh` for Linux without GPU with deleting the block below:

```
# check whether Apple Silicon (M1 mac) or Intel Mac
arch_name="$(uname -m)"

if [ "${arch_name}" = "x86_64" ]; then
    if [ "$(sysctl -in sysctl.proc_translated)" = "1" ]; then
        echo "Running on Rosetta 2"
    else
        echo "Running on native Intel"
    fi
elif [ "${arch_name}" = "arm64" ]; then
    echo "Running on Apple Silicon (M1 mac)"
    echo "This installer is only for intel Mac. Use install_colabfold_M1mac.sh to install on this Mac."
    exit 1
else
    echo "Unknown architecture: ${arch_name}"
    exit 1
fi
```

Also, the following modification for `runner.py` may be required.

```
### Check your OS for localcolabfold
import platform
pf = platform.system()
if pf == 'Windows':
  print('ColabFold on Windows')
elif pf == 'Darwin':
  print('ColabFold on Mac')
  device="cpu"
elif pf == 'Linux':
  print('ColabFold on Linux')
  device="cpu"  # Use CPU on Linux
#%%
```

Try it.

**Comment by zwehrspan** [comment]
Thank you for sending those code changes. I tried deleting that code chunk from `install_colabfold_intelmac.sh` and changing the `runner.py` script, but localcolabfold failed to run (with the error: `ModuleNotFoundError: No module named 'tensorflow'`). However, I read [this issue](https://github.com/deepmind/alphafold/issues/149), and set the environment variables `TF_FORCE_UNIFIED_MEMORY` and `XLA_PYTHON_CLIENT_MEM_FRACTION`. Setting these environment variables solves my problem by using the CPU RAM in conjunction with the GPU RAM with the Linux version, so I no longer need the Linux version to work only on the CPU. Thanks again for your input!
