### ISSUE TITLE
Running with CPU

### ISSUE THREAD

**Issue by ecapriotti** [YoshitakaMo/localcolabfold#63]
Hi ,
I am running localcolabfold with the option --cpu to avoid the usage pf GPU, nevertheless when the program run with the option 
--amber the program crash because con not found any GPU.
The error is the following:

file "/share/apps/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 13232, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
simtk.openmm.OpenMMException: Error initializing CUDA: CUDA_ERROR_NO_DEVICE (100) at /home/conda/feedstock_root/build_artifacts/openmm_1622798721771/work/platforms/cuda/src/CudaContext.cpp:138

Thanks for your attention

**Comment by YoshitakaMo** [comment]
The error may be caused by forcing to use GPU for the amber-relaxation process.
Please type the command below and try your calculation again.
```
# specify your directory
COLABFOLDDIR=/path/to/your/colabfold_batch
# Use CPU for amber-relaxation process
sed -i -e 's/CUDA/CPU/g' ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py
```
