### ISSUE TITLE
Bug: Persistant minimization error when using the --amber flag.

### ISSUE THREAD

**Issue by arpeggio9** [YoshitakaMo/localcolabfold#71]
This error has been seen before, but I've not seen a way to solve it from the replies to those who saw it before. I have installed localcolabfold according to the instructions for Linux and colabfold works fine until the --amber flag is employed, when this error appears:

colabfold_batch/colabfold-conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py", line 415, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

This error occurs whatever protein sequence is used (I've tested it with 1r0j and 2vb1(FASTA sequences derived from the PDB structures)), but I have researchers who have seen it with new sequences (where no structure is available). Command line options used : --amber --templates --num-recycle 3

It appears that when called, _openmm_minimize does not return anything which causes the exception to be raised. Either there is an internal failure within this subroutine or the structure is already at its global minimum, so it can't do anything further. If this was the case then it would be helpful if the exception could suggest this as, at the moment my researchers just see the error. If this is expected behavior, then can it be assumed the unminimized structures are correct and further minimization is unnecessary as clarity in this point would be appreciated.

I am running localcolabfold on a server with 32-cores 512GB RAM and an A100 GPU on CentOS 7 using the version of CUDA installed by the localcolabfold installation script.

Any assistance in solving this problem (or if minimization could be safely avoided) would be greatly appreciated.

Many thanks.

**Comment by YoshitakaMo** [comment]
Is it related to https://github.com/YoshitakaMo/localcolabfold/issues/37 ?
This bug occurs if you moved your colabfold_batch directory somewhere after installation. Do not move it after installation.

**Comment by arpeggio9** [comment]
Dear Dr. Moriwaki,
Many thanks for your reply. I did see the reply from #37 and did wonder if it might be NFS-related, so I installed it on the local disk in the server I'm running it on. I did not move the installation directory after the installation had completed, but I still got this error and this has also been also true where it has been installed on share filesystems; the installation directory is not moved after installation, but the error occurs. May I ask how you are installing localcolabfold, if you are not finding this error with the --amber lag after installation, as it appears consistent for me wherever I install it.
Kind Regards.

**Comment by YoshitakaMo** [comment]
> May I ask how you are installing localcolabfold

I installed it by executing `bash install_colabbatch_linux.sh` on my Ubuntu 20.04 `${HOME}/Desktop`. Both `nvidia-smi` and `nvcc --version` showed the GPU information correctly (CUDA Driver and Cuda compiler driver >= 11.1).

> Either there is an internal failure within this subroutine or the structure is already at its global minimum, so it can't do anything further. If this was the case then it would be helpful if the exception could suggest this as, at the moment my researchers just see the error. If this is expected behavior, then can it be assumed the unminimized structures are correct and further minimization is unnecessary as clarity in this point would be appreciated.

Even if you input the same sequence and template as those registered in PDB, this doesn't happen. Namely, the installation does not seem to be working perfectly.
I didn't think the issue is caused by NFS, but I have no idea to solve it now.

I think this issue is not caused by localcolabfold itself, but by the machine environment. There are the same error reports in  https://github.com/deepmind/alphafold/issues?q=is%3Aissue+minimization+failed , and the answer is to turn off the relaxation. In other words, it seems the root cause is not clarified even by AlphaFold developers.
