### ISSUE TITLE
Switching between GPU and CPU for amber relax.

### ISSUE THREAD

**Issue by ajasja** [YoshitakaMo/localcolabfold#72]
**Feature enhancement**
Currently the amber relaxation is switched between GPU and CPU using `sed`.

However, the Alphafold amber relax code has a GPU relax flag now
https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/run_alphafold.py#L386

So is the sed hack still necessary?

**Comment by ajasja** [comment]
Using `OPENMM_DEFAULT_PLATFORM ` would also be a good workaround. http://docs.openmm.org/7.0.0/userguide/application.html

**Comment by YoshitakaMo** [comment]
The current version has `--use-gpu-relax` option to control it. Please update your colabfold and try it.
