### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by anpanche** [YoshitakaMo/localcolabfold#78]
**Describe the bug**
Hi @YoshitakaMo ,
I am trying to install localcolebfold on my Mac and I want to run rosetafold and alphafold using cpu.
I followed all the steps for Mac with silicon chip and succesfully installed colabfold_batch (according to the message I got). But when I am running the commenad for prediction it is giving the following error,

/Users/arcsan/Desktop/multimers/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/jax/_src/lib/__init__.py:32: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "
Traceback (most recent call last):
  File "/Users/arcsan/Desktop/multimers/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 5, in <module>
    from colabfold.batch import main
  File "/Users/arcsan/Desktop/multimers/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 25, in <module>
    from alphafold.notebooks.notebook_utils import get_pae_json
ModuleNotFoundError: No module named 'alphafold'

Please let me know how can I resolve this issues.
Thanks in advance.

**Comment by nspyf** [comment]
It seems to be an installation problem.
The installation will not be canceled even If some steps failed. And the failed steps in the installation message is not obvious.
I recommend to remove the related directories, retry the installation and check the message carefully.
By the way, the title 'Bug:' is broad. 'ModuleNotFoundError: No module named 'alphafold'' is better.

**Comment by YoshitakaMo** [comment]
The bug is now fixed. Please try the latest installer for M1 Mac and try again.

**Comment by anpanche** [comment]
Thanks. I will do the installation again and check.
