### ISSUE TITLE
Templates are ignored?

### ISSUE THREAD

**Issue by luhong88** [YoshitakaMo/localcolabfold#82]
I'm trying to do a structure prediction with a custom template mmCIF file and no MSA. I tested the template file using the `colabfold` notebook and it worked well. The command I used for `localcolabfold` was
```
colabfold_batch input/KaiB_WT.a3m output/ \
                --templates --custom-template-path templates/ \
                --msa-mode single_sequence \
                --num-recycle 3 --num-models 5 \
                --model-type AlphaFold2-ptm --rank plddt
```
but it seems that the output models are the same as those without any templates (the log file does not say anything about templates either). I also tried just using `--templates` but not `--custom-template-path` and the results were the same.

The version I'm using is `colabfold 1.3.0 (d6b0670552ce3f39e20b69f9e01521ca39562336)`.

**Comment by YoshitakaMo** [comment]
Is this discussion ( https://github.com/sokrypton/ColabFold/issues/177 ) helpful?
If your custom template is successfully used in the prediction, the log says like this:
```
2022-03-17 09:24:44,089 Sequence 0 found templates: [b'9xzx_A' b'9xzx_A' b'9xzx_A' b'9xzx_A']
```

**Comment by luhong88** [comment]
No after digging around in the code I think the issue is this: if I'm using a fasta input file, localcolabfold seems to have to query a server for MSA and pdb70 templates, even if I specify `single_sequence` for `msa_mode` and provide `--custom-template-path` (as far as I can tell these query results are not used anyway?) This was a problem when I submitted the calculation to a compute cluster where the nodes did not have internet access. which resulted in error messages about unable to establish connection with the server.
