### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_gpu'

### ISSUE THREAD

**Issue by cleffyheft** [YoshitakaMo/localcolabfold#83]
Hi, I tried running localcolabfold on both my M1 Pro MacBook Pro and my M1 mac mini but they both gave me this error. I've tried troubleshooting it but I'm running out of ideas. Can I get some help?

The line I used to run the program was:
```
colabfold_batch --ambers --templates --num-recycle 3 input output
```

Things I've tried:
--cpu
--use-gpu-relax
- updating tensorflow
- updating scipy

Error message:
```
warnings.warn("""
Traceback (most recent call last) :
  File "/Users/kennychin/Alphafold/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/Users/kennychin/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/sit
e-packages/colabfold/batch.py", line 1482, in main
    run(
  File "/Users/kennychin/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/sit
e-packages/colabfold/batch.py", line 1172, in run
    outs, model_rank = predict_structure(
  File "/Users/kennychin/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/sit
e-packages/colabfold/batch.py", line 350, in predict_structure
     amber_relaxer = relax.AmberRelaxation(
TypeError: _init__() got an unexpected keyword argument 'use_gpu'
```

**Comment by YoshitakaMo** [comment]
Thank you for your report!! This issue was caused by the installation of 'alphafold-colabfold' package pinned to a specific commit.
I've updated both the installer and updater script for M1 Mac. Please download the latest one from this repository and run the updater to fix this issue.
