### ISSUE TITLE
[Errno 2] No such file or directory: 'hhsearch': 'hhsearch'

### ISSUE THREAD

**Issue by WHEREISSHE** [YoshitakaMo/localcolabfold#87]
When I trying to make prediction, the error---`[Errno 2] No such file or directory: 'hhsearch': 'hhsearch'`---occurred. I found `hhsuit` included in my `conda list`, so what caused this? And how could I fix it? Appreciated for any advice.

**Comment by Jmonod** [comment]
May I ask how you resolve this issue ? I'm having the same error

**Comment by Jmonod** [comment]
I resolved my issue. The export path towards localcolabfold folder was wrong.
