### ISSUE TITLE
Storing intermediate recycles?

### ISSUE THREAD

**Issue by rkruegs123** [YoshitakaMo/localcolabfold#88]
Rather than just save the output of the Nth recycle, I want to save the current state at all 0-N recycles. Is there a way to do this without running N+1 separate jobs?

**Comment by YoshitakaMo** [comment]
Now the feature has been available with `--save-recycles` argument implemented in the latest version. See also the [change log](https://github.com/sokrypton/ColabFold/wiki/v1.5.0) .
