### ISSUE TITLE
Prediction mode selection

### ISSUE THREAD

**Issue by IlyesAbdelhamid** [YoshitakaMo/localcolabfold#89]
Two protein complex prediction modes have been implemented in ColabFold. One is based on AlphaFold-multimer and the other is based on the manipulation of residue index in the original AlphaFold2 model. In localcolabfold, how can I select either options? And what is the default prediction mode?
Thank you in advance for your reply. 

Sincerely,
Ilyes

**Comment by YoshitakaMo** [comment]
> Two protein complex prediction modes have been implemented in ColabFold. One is based on AlphaFold-multimer and the other is based on the manipulation of residue index in the original AlphaFold2 model.

Do you mean "AlphaFold2-ptm" and "AlphaFold-multimer-v[1,2]", which can be specified at "Advanced settings - model_type" in the [ColabFold Notebook](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb)? If so, you can select using `--model-type` argument in localcolabfold (default is `auto` ).

```bash
$ colabfold_batch --help
...
  --model-type {auto,AlphaFold2-ptm,AlphaFold2-multimer-v1,AlphaFold2-multimer-v2}
                        predict strucutre/complex using the following
                        model.Auto will pick "AlphaFold2" (ptm) for structure
                        predictions and "AlphaFold2-multimer-v2" for
                        complexes.
...
```

Namely, `AlphaFold2-ptm` is automatically used for monomeric predictions, and  `AlphaFold2-multimer-v2` for complexes. 'AlphaFold2-multimer-v2' is a default parameter set for complex predictions in AlphaFold v2.2.0. 'v1' is an experimental parameter set used up to v2.1.1 and is generally less accurate than v2.
