### ISSUE TITLE
Question:Error! colabfold-conda directory is not present in .

### ISSUE THREAD

**Issue by shijifeihu** [YoshitakaMo/localcolabfold#93]
**What is your question?**
when run update_linux.sh

it pops up :Error! colabfold-conda directory is not present in .:

However, you do see the folder exis using ls

**Computational environment**
 - OS: [e.g. Ubuntu 20.04, Windows11 & WSL2, ]
 - CUDA version if Linux (Use `nvidia-smi` to check) Cuda 11.7

**To Reproduce**
bin        colabfold-conda  matplotlib                 stereo_chemical_props.txt.1  update_linux.sh
colabfold  conda            stereo_chemical_props.txt  stereo_chemical_props.txt.2

**Expected behavior**

**Comment by YoshitakaMo** [comment]
Try
```
# change directory to your colabfold_batch directory
cd /path/to/colabfold_batch
# Do not forget '.' after './update_linux.sh'
./update_linux.sh .
```

**Comment by shijifeihu** [comment]
thanks for your reply. Already tried cd to the colab_batch folder and double check the line still got the same error.

I rerun the installation, it's the same issue.
For now, i think i can keep the update by re installation.when there is a significant release

Thanks,
Hu



---- Replied Message ----
| From | Yoshitaka ***@***.***> |
| Date | 07/04/2022 01:14 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [YoshitakaMo/localcolabfold] Question:Error! colabfold-conda directory is not present in . (Issue #93) |

Try

# change directory to your colabfold_batch directory
cd /path/to/colabfold_batch
# Do not forget '.' after './update_linux.sh'
./update_linux.sh .
