### ISSUE TITLE
Question: socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by JOJO-wc-rabbit** [YoshitakaMo/localcolabfold#96]
Hi,

I got the error below while submitting the test code (`colabfold_batch --num-recycle 1 4UUZ.fasta output`) on a cluster server (ssh, non-root). Is there any solution please?

![微信截图_20220718155511](https://user-images.githubusercontent.com/61336971/179468856-dab8f4f2-81ee-45d8-9528-cfa9e97b7b9a.png)

Thanks.

**Comment by YoshitakaMo** [comment]
I guess the compute node of your cluster server is not connected to the Internet. It is often the case that the head node (login node) is connected to the Internet, but its compute nodes do not have access to the Internet.

**Comment by JOJO-wc-rabbit** [comment]
> 

OK i see，thx！
