### ISSUE TITLE
Memory resources for large complexes

### ISSUE THREAD

**Issue by dpretorius** [YoshitakaMo/localcolabfold#97]
I am trying to run a trimeric complex of 2854 residues (very large). I am getting a consistent memory error when doing so:

**2022-07-18 12:38:21,607 Could not predict nifH2D2K2F2. Not Enough GPU memory? RESOURCE_EXHAUSTED: Failed to allocate request for 36.06GiB (38718784536B) on device ordinal 0**
**BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.54GiB
              constant allocation:    24.4KiB
        maybe_live_out allocation:    7.83GiB
     preallocated temp allocation:   36.06GiB
  preallocated temp fragmentation:     1.3KiB (0.00%)
                 total allocation:   48.43GiB
              total fragmentation:    3.92GiB (8.09%)**

I am using a HPC system with Linux. I have 4 Nvidia RTX6000 GPUs, each with 24 Gb and RAM of 96 Gb.
In my submission script I am defining: 

**module load cuda/11.2.2
module load cudnn/8.2.4
export XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1
export TF_FORCE_UNIFIED_MEMORY="1"
export XLA_PYTHON_CLIENT_MEM_FRACTION="4.0"
export XLA_PYTHON_CLIENT_ALLOCATOR="platform"
export TF_FORCE_GPU_ALLOW_GROWTH="true"** 

However, although I am allowing it to use a significant amount of my host memory it does not seem to access it. The 36 Gb that it fails at is: 24 Gb ( 1 GPU memory) + 12 Gb (0.5 times the GPU memory).

Why does it seem to be limited to 36 Gb when I have more and am allowing it to be used?

What else can I do to extend the memory?

Thanks for the project!

**Comment by YoshitakaMo** [comment]
As described in FAQ, AlphaFold and colabfold can't use two or more GPUs simultaneously. I am also using a GPU with 24GB of memory, but it cannot predict structures beyond approximately 2500 residues. One solution is to use a GPU with more memory.

**Comment by dpretorius** [comment]
Thank you for such a quick response @YoshitakaMo!

But what about instances where AF is said to have multi-GPU capacity to extend the memory for long sequences:

"AlphaFold supports multi-GPU usage, which means that when using two GPUs, the GPU memory can be almost doubled. Like this, longer sequences can be processed on a cluster with limited individual GPU memory"

"To prevent out-of-memory errors, long sequences were assigned to multi-GPU workers. Specifically, sequences of length 1,401–2,000 residues were processed by workers with two GPUs, and those of length 2,001–2,700 residues by workers with four GPUs"

Sources:
https://elearning.bits.vib.be/courses/alphafold/lessons/alphafold-on-the-hpc/topic/computational-limits/
https://www.nature.com/articles/s41586-021-03828-1#ref-CR2

**Comment by YoshitakaMo** [comment]
The description you referred to also discussed on the issue page of the original AlphaFold repository ( https://github.com/deepmind/alphafold/issues/490 ). But, as far as the colabfold developers (including me) know, it uses only a GPU even though there are multiple GPUs available. I doubt that it is true as discussed there. 

Of course, a lot of people are hoping that AlphaFold will be able to use multiple GPUs to increase the limitation of sequence length. I also hope it will be implemented in the near future.
