### ISSUE TITLE
File name too long issue

### ISSUE THREAD

**Issue by mingyujj** [YoshitakaMo/localcolabfold#99]
I've tried the ffa2.fasta example. However I got the [ **OSError: [Errno 63] File name too long:** ]  error
Can anybody help?

(base) user@MacBook-Pro-5 colabfold_batch % ./bin/colabfold_batch --amber --templates --num-recycle 3 --cpu /Users/user/Projects/Alphafold/ffa2.fasta FFA2output
2022-07-21 16:37:57,831 Running colabfold 1.3.0 (26de12d3afb5f85d49d0c7db1b9371f034388395)
/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/jax/_src/lib/__init__.py:34: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "
WARNING: You are welcome to use the default MSA server, however keep in mind that it's a limited shared resource only capable of processing a few thousand MSAs per day. Please submit jobs only from a single IP address. We reserve the right to limit access to the server case-by-case when usage exceeds fair use.

If you require more MSAs:

* You can precompute all MSAs with `colabfold_search` or

* You can host your own API and pass it to `--host-url`
2022-07-21 16:38:38,588 Found 8 citations for tools or databases
Traceback (most recent call last):
  File "/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/bin/colabfold_batch", line 8, in <module>
    sys.exit(main())
  File "/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 1728, in main
    run(
  File "/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/site-packages/colabfold/batch.py", line 1298, in run
    if keep_existing_results and result_zip.is_file():
  File "/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/Users/user/Projects/Alphafold/colabfold_batch/colabfold-conda/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
OSError: [Errno 63] File name too long: 'FFA2output/3kud_complex_MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLC_VFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLV_REIRQH__PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDF_L.result.zip'

**Comment by YoshitakaMo** [comment]
Maybe the format of your input file `ffa2.fasta` is wrong. It should be:

```
>3kud_complex
MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLVREIRQH:
PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKKLKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDFL
```

Because colabfold uses the first line starting with `>` of input fasta file as the name of output result files, it should be short, preferably.

**Comment by mingyujj** [comment]
Thanks for your help. However it had an error of
ValueError: operands could not be broadcast together with shapes (3205,251) (1,247) (3205,251) 
2022-07-21 23:41:27,872 Done

**Comment by YoshitakaMo** [comment]
Please, let me show the input fasta file and the complete log.
